// src/tabs/Demo.js — Live inference demo page.
// Lets the user supply up to two fundus images (left + right eye) of one
// patient, runs the trained model on the backend, and lets the user confirm or
// reject the result. Confirmed / corrected cases are appended to a local
// relabeling buffer that can be exported as JSONL for further training.
//
// A *patient case* is opened on the backend the moment the first image that
// passes the fundus check lands in a slot (server/app/cases.py). Its id then
// rides along on every later call for this patient, so the originals, the cached
// preprocessing stages, the attention maps, the prediction and — the reason the
// store exists — the ophthalmologist's verdict all end up in one directory on
// the server instead of dying with the browser tab.

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { C, GRADE_COLORS, GRADE_INK } from '../data';
import { Card, Sec, Note } from '../components';
import { useLang } from '../i18n';
import { SEGMENTATION_PATIENTS } from './_segmentationSamples';
import { matchIdridUpload } from './_idridUpload';
import { analyzeFundus } from './_analyzeFundus';
import {
  predictPatient, getHealth, getPassword, setPassword, verifyPassword,
  openCaseImage, submitCaseFeedback, retractCaseFeedback, getCaseStats,
  getCaseVerdicts, fetchCaseReport,
} from './_apiPredict';
import VisionWidget from './_VisionWidget';
import LiveVisualizationBlock from './_LiveGradcam';

// ---------------------------------------------------------------------------
// Walk-through cases that share an image with the preprocessing-pipeline
// gallery. Each entry exposes pre-generated Grad-CAM heatmap + attention
// overlay rendered by `demo/web/public/pipeline/helpers/s8_results.py` (proxy
// heatmap derived from flat-field anomaly detection; not a real Grad-CAM
// from a trained checkpoint).
// ---------------------------------------------------------------------------
const WALKTHROUGH_POOL = [
  { id: 'walk_dr00', grade: 0, left: 'pipeline/dr00/input/left.png', right: 'pipeline/dr00/input/right.png', explainable: true, resultsBase: 'pipeline/dr00/results' },
  { id: 'walk_dr01', grade: 1, left: 'pipeline/dr01/input/left.png', right: 'pipeline/dr01/input/right.png', explainable: true, resultsBase: 'pipeline/dr01/results' },
  { id: 'walk_dr02', grade: 2, left: 'pipeline/dr02/input/left.png', right: 'pipeline/dr02/input/right.png', explainable: true, resultsBase: 'pipeline/dr02/results' },
  { id: 'walk_dr03', grade: 3, left: 'pipeline/dr03/input/left.png', right: 'pipeline/dr03/input/right.png', explainable: true, resultsBase: 'pipeline/dr03/results' },
  { id: 'walk_dr04', grade: 4, left: 'pipeline/dr04/input/left.png', right: 'pipeline/dr04/input/right.png', explainable: true, resultsBase: 'pipeline/dr04/results' },
];

// ---------------------------------------------------------------------------
// IDRiD image pool for the Random button, sourced from `_segmentationSamples.js`
// (regenerated by `demo/web/scripts/prepare_segmentation_pairs.py`).
//
// IDRiD is monocular, so each entry is a SYNTHETIC bilateral patient: one
// left-eye + one right-eye image, laterality measured from the optic-disc mask
// (disc nasal to the macula) and the two eyes matched on retinal colour so a
// drawn pair reads as one person. The Random button inserts these images as
// PLAIN samples (no ground-truth payload): they are detected, drag-correctable,
// and DR-graded exactly like an uploaded snapshot — the helper data carried in
// the manifest (OD centre, FOV mask) is intentionally not supplied.
// ---------------------------------------------------------------------------
let lastIdridIdx = -1;
function pickRandomIdridPatient() {
  if (!SEGMENTATION_PATIENTS || SEGMENTATION_PATIENTS.length === 0) return null;
  let idx;
  do {
    idx = Math.floor(Math.random() * SEGMENTATION_PATIENTS.length);
  } while (SEGMENTATION_PATIENTS.length > 1 && idx === lastIdridIdx);
  lastIdridIdx = idx;
  return SEGMENTATION_PATIENTS[idx];
}

// Walkthrough fallback (used only when SEGMENTATION_PATIENTS is empty).
let lastWalkIdx = -1;
function pickRandomWalkthrough(pool) {
  if (!pool || pool.length === 0) return null;
  let idx;
  do {
    idx = Math.floor(Math.random() * pool.length);
  } while (pool.length > 1 && idx === lastWalkIdx);
  lastWalkIdx = idx;
  return pool[idx];
}

// ---------------------------------------------------------------------------
// Normalize the backend's PatientPredictionResponse (snake_case, no per-eye
// src) into the shape the Result panel renders: { pred, probs, confidence,
// latencyMs, perEye: [{ eye, src, result }] }.
// ---------------------------------------------------------------------------
function normalizeApiResult(r, eyes) {
  return {
    pred: r.pred,
    probs: r.probs,
    confidence: r.confidence,
    latencyMs: r.latency_ms,
    perEye: (r.per_eye || []).map(p => ({
      eye: p.eye,
      src: (eyes.find(e => e.eye === p.eye) || {}).src,
      result: {
        pred: p.pred,
        probs: p.probs,
        confidence: p.confidence,
        latencyMs: p.latency_ms,
      },
    })),
  };
}

// ---------------------------------------------------------------------------
// UI sub-components
// ---------------------------------------------------------------------------
function EyeSlot({ label, eye, image, onPick, onClear, onSwap, t }) {
  const inputRef = useRef(null);
  const [dims, setDims] = useState(null);
  // "Keep" dismisses the wrong-slot warning for the current image only.
  const [dismissed, setDismissed] = useState(false);
  const [drag, setDrag] = useState(false);
  // Reset the size badge and dismissed-warning state when the loaded image
  // changes (or is cleared) so we never carry the previous image's dimensions
  // or a stale dismissal into a freshly loaded image. (Extracted to a variable
  // so react-hooks/exhaustive-deps can statically check it — a bare
  // `image && image.src` in the deps array trips the CI build under CI=1.)
  const imageSrc = image && image.src;
  useEffect(() => { setDims(null); setDismissed(false); }, [imageSrc]);

  const onChange = (e) => {
    const file = e.target.files && e.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = async (ev) => {
      const checks = await analyzeFundus(ev.target.result);
      onPick({ src: ev.target.result, name: file.name, fromUpload: true, checks });
    };
    reader.readAsDataURL(file);
  };
  const onDrop = (e) => {
    e.preventDefault();
    const file = e.dataTransfer.files && e.dataTransfer.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = async (ev) => {
      const checks = await analyzeFundus(ev.target.result);
      onPick({ src: ev.target.result, name: file.name, fromUpload: true, checks });
    };
    reader.readAsDataURL(file);
  };

  // Derived check state for the chips below the preview.
  const checks = image && image.checks;
  const showNotFundus = !!(checks && checks.isFundus === false);
  const showWrongSide = !!(
    checks && checks.laterality && checks.laterality !== eye &&
    checks.confidence > 0.5 && !dismissed
  );
  const wrongSideMsg = showWrongSide
    ? t('demo.check.wrongSide').replace('{eye}', t('demo.check.eye.' + checks.laterality))
    : '';

  const openPicker = () => inputRef.current && inputRef.current.click();
  const code = eye === 'right' ? 'OD' : 'OS';

  return (
    <div className="eye-slot" style={{ flex: 1, minWidth: 220 }}>
      <div className="eye-label">
        <span className="eye-code">{code}</span>
        <span className="eye-name" title={label}>{t('demo.eye.' + eye)}</span>
        {dims && (
          <span style={{ marginLeft: 'auto', fontSize: 11, color: 'var(--color-text-tertiary)' }}>
            {dims.w} × {dims.h} px
          </span>
        )}
      </div>
      <div
        role="button"
        tabIndex={0}
        aria-label={`${label}: ${image ? image.name || '' : t('demo.dropHere')}`}
        onClick={openPicker}
        onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); openPicker(); } }}
        onDragOver={(e) => { e.preventDefault(); if (!drag) setDrag(true); }}
        onDragLeave={() => setDrag(false)}
        onDrop={(e) => { setDrag(false); onDrop(e); }}
        // Fixed 1:1 frame regardless of image presence — keeps the form height
        // stable so the Run button and result don't jump when an image loads.
        // A loaded photo sits on dark slate rather than black: fundus photos
        // carry their own black border, and slate still reveals its true shape.
        className={'eye-frame' + (image ? '' : ' empty') + (drag ? ' drag' : '')}
      >
        {image ? (
          <img
            src={image.src}
            alt={label}
            onLoad={(e) => setDims({ w: e.target.naturalWidth, h: e.target.naturalHeight })}
            style={{ width: '100%', height: '100%', objectFit: 'contain', display: 'block' }}
          />
        ) : (
          <>
            {/* Empty state: the 45° fundus field as a reticle, with the optic
                disc on this eye's nasal side and the fovea at the centre — the
                shape of what belongs in the slot. */}
            <svg className="reticle" viewBox="0 0 100 100" aria-hidden="true">
              <circle cx="50" cy="50" r="49" fill="none" stroke="currentColor" strokeWidth="0.7" strokeDasharray="2 2.2" />
              <line x1="50" y1="44" x2="50" y2="56" stroke="currentColor" strokeWidth="0.6" />
              <line x1="44" y1="50" x2="56" y2="50" stroke="currentColor" strokeWidth="0.6" />
              <circle cx={eye === 'right' ? 74 : 26} cy="47" r="6" fill="none" stroke="currentColor" strokeWidth="0.7" />
            </svg>
            <div className="eye-empty-copy">
              <strong className="copy-long">{t('demo.dropHere')}</strong>
              <strong className="copy-short">{t('demo.tapToAdd')}</strong>
              <span>{t('demo.formats')}</span>
            </div>
          </>
        )}
        <input ref={inputRef} type="file" accept="image/*" onChange={onChange} style={{ display: 'none' }} tabIndex={-1} />
      </div>

      {/* Validation chips (uploaded images only). Warn, never block. */}
      {showNotFundus && (
        <div style={{
          marginTop: 6, padding: '4px 8px', borderRadius: 4, fontSize: 10,
          background: C.amberBg, color: C.amberT, border: `1px solid ${C.amber}`,
        }}>
          ⚠ {t('demo.check.notFundus')}
        </div>
      )}
      {showWrongSide && (
        <div style={{
          marginTop: 6, padding: '6px 8px', borderRadius: 4, fontSize: 10,
          background: C.redBg, color: C.redT, border: `1px solid ${C.red}`,
          display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap',
        }}>
          <span style={{ flex: 1, minWidth: 120 }}>⚠ {wrongSideMsg}</span>
          <button
            onClick={onSwap}
            style={{
              padding: '2px 8px', fontSize: 10, fontWeight: 600,
              background: C.red, color: 'white', border: 'none',
              borderRadius: 3, cursor: 'pointer',
            }}
          >
            {t('demo.check.swap')}
          </button>
          <button
            onClick={() => setDismissed(true)}
            style={{
              padding: '2px 8px', fontSize: 10,
              background: 'transparent', color: C.redT,
              border: `1px solid ${C.red}`, borderRadius: 3, cursor: 'pointer',
            }}
          >
            {t('demo.check.keep')}
          </button>
        </div>
      )}
      {/* Always reserve the Clear button's vertical space so the form height
          doesn't change when an image is added/removed. The button is only
          visible (and clickable) when there is something to clear. */}
      <button
        onClick={onClear}
        disabled={!image}
        className="btn btn-quiet btn-sm"
        style={{ marginTop: 8, visibility: image ? 'visible' : 'hidden' }}
      >
        {t('demo.clear')}
      </button>
    </div>
  );
}

// The ICDR grade scale — the page's one signature figure. Five steps in the
// grade ramp, the model's probability standing on each, and the referral
// threshold drawn between DR1 and DR2. Columns are scaled to the tallest so the
// shape reads at a glance; the printed percentages carry the absolute values.
function GradeScale({ probs, pred, t }) {
  const top = Math.max(...probs, 1e-6);
  return (
    <div className="grade-scale" role="img" aria-label={
      probs.map((p, g) => `${t('demo.gradeShort.' + g)} ${(p * 100).toFixed(1)}%`).join(', ')
    }>
      <div className="gs-cols">
        {probs.map((p, g) => (
          <div key={g} className={'gs-col' + (g === pred ? ' pred' : '')}>
            <div className="gs-pct">{(p * 100).toFixed(p < 0.1 ? 1 : 0)}%</div>
            <div className="gs-bar" style={{ height: `${Math.max(2, (p / top) * 70)}%`, background: GRADE_COLORS[g] }} />
          </div>
        ))}
        <div className="gs-threshold"><span>{t('demo.scale.threshold')}</span></div>
      </div>
      <div className="gs-track">
        {GRADE_COLORS.map((c, g) => <div key={g} className="gs-step" style={{ background: c }} />)}
      </div>
      <div className="gs-labels">
        {probs.map((_, g) => (
          <div key={g} className="gs-label">
            <b>{g}</b>
            {gradeName(t, g)}
          </div>
        ))}
      </div>
    </div>
  );
}

// "DR2 — Moderate NPDR" → "Moderate NPDR" (both languages share the format).
function gradeName(t, g) {
  const full = t('demo.grade.' + g);
  const i = full.indexOf(' — ');
  return i >= 0 ? full.slice(i + 3) : full;
}

function HeatmapPair({ resultsBase, side, t }) {
  const base = process.env.PUBLIC_URL + '/' + resultsBase;
  return (
    <div style={{ flex: 1, minWidth: 220 }}>
      <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-text-secondary,#666)', marginBottom: 6 }}>
        {t(side === 'left' ? 'demo.leftEye' : 'demo.rightEye')}
      </div>
      <figure style={{ margin: 0 }}>
        {/* Analysis-frame overlay — mirror left eyes back to the original
            orientation (matches the live Grad-CAM block). */}
        <img
          src={`${base}/attention_overlay/${side}.png`}
          alt={`Attention overlay ${side}`}
          style={{
            width: '100%', display: 'block', borderRadius: 6, background: '#000',
            transform: side === 'left' ? 'scaleX(-1)' : undefined,
          }}
        />
        <figcaption style={{ fontSize: 10, marginTop: 4, color: 'var(--color-text-secondary,#666)' }}>
          {t('demo.viz.overlay')}
        </figcaption>
      </figure>
    </div>
  );
}

function VisualizationBlock({ caseRef, leftPresent, rightPresent, t }) {
  const explainable = caseRef && caseRef.explainable && caseRef.resultsBase;
  return (
    <div style={{ marginTop: 14 }}>
      <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-text-secondary,#666)', marginBottom: 6 }}>
        {t('demo.viz.title')}
      </div>
      {explainable ? (
        <>
          <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
            {rightPresent && <HeatmapPair resultsBase={caseRef.resultsBase} side="right" t={t} />}
            {leftPresent && <HeatmapPair resultsBase={caseRef.resultsBase} side="left" t={t} />}
          </div>
          <Note>{t('demo.viz.disclaimer')}</Note>
        </>
      ) : (
        <Note>{t('demo.viz.unavailable')}</Note>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Statistics over the whole case store (GET /api/cases/stats).
//
// These counters are computed from the case directories on the server, not from
// this tab: clearing the relabeling buffer, reloading the page or opening the
// demo on another machine leaves them intact. The buffer above counts what this
// session labelled; this counts what the study holds.
// ---------------------------------------------------------------------------
function CaseStatsPanel({ stats, t }) {
  if (!stats) return null;
  const decided = stats.confirmed + stats.rejected;
  const agreement = stats.agreement == null ? '—' : `${(stats.agreement * 100).toFixed(0)}%`;
  // Scale the grade bars to the busiest grade (never divide by zero).
  const maxGrade = Math.max(1, ...stats.grades);
  return (
    <div style={{ marginTop: 24, paddingTop: 16, borderTop: '1px solid var(--color-border-tertiary)' }}>
      <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--color-text-primary)', marginBottom: 10 }}>
        {t('demo.stats.title')}
      </div>
      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
        <Card
          label={t('demo.stats.patients')} value={stats.patients} color="teal"
          sub={`${stats.images} ${t('demo.stats.images')}`}
        />
        <Card
          label={t('demo.stats.runs')} value={stats.predictions} color="blue"
          sub={`${stats.corrections} ${t('demo.stats.corrections')}`}
        />
        <Card
          label={t('demo.stats.verdicts')} value={stats.verdicts} color="purple"
          sub={`${stats.reviewed_patients} ${t('demo.stats.reviewed')}`}
        />
        <Card
          label={t('demo.stats.confirmed')} value={stats.confirmed} color="green"
          sub={`${stats.rejected} ${t('demo.stats.rejected')}`}
        />
        <Card
          label={t('demo.stats.agreement')} value={agreement} color="amber"
          sub={decided ? `n = ${decided}` : t('demo.stats.noVerdicts')}
        />
      </div>

      {/* Reviewed patients per DR grade — the reviewer's grade, not the model's. */}
      {stats.reviewed_patients > 0 && (
        <div style={{ marginTop: 12 }}>
          <div style={{ fontSize: 10, fontWeight: 600, color: 'var(--color-text-secondary,#666)', marginBottom: 5 }}>
            {t('demo.stats.gradeDist')}
          </div>
          {stats.grades.map((n, g) => (
            <div key={g} style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 3 }}>
              <div style={{ fontSize: 10, color: 'var(--color-text-secondary,#666)', minWidth: 36 }}>
                {t('demo.gradeShort.' + g)}
              </div>
              <div style={{
                flex: 1, height: 14, background: 'var(--color-background-secondary,#eeede9)',
                borderRadius: 3, position: 'relative', overflow: 'hidden',
              }}>
                <div style={{ width: `${(n / maxGrade) * 100}%`, height: '100%', background: GRADE_COLORS[g] }} />
                <span style={{
                  position: 'absolute', right: 5, top: '50%', transform: 'translateY(-50%)',
                  fontSize: 9, fontWeight: 600, color: 'var(--color-text-primary,#333)',
                }}>
                  {n}
                </span>
              </div>
            </div>
          ))}
        </div>
      )}

      {stats.last_activity_utc && (
        <div style={{ fontSize: 11, color: 'var(--color-text-tertiary)', marginTop: 8 }}>
          {t('demo.stats.lastActivity')}: {new Date(stats.last_activity_utc).toLocaleString()}
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main page
// ---------------------------------------------------------------------------
// Access-code screen (TASK-Demo §C.2). Shown only when the backend reports
// `requires_password` and no valid code is held yet. A 4-digit PIN — no
// accounts, no login flow — adequate for a ~15-person academic beta.
//
// PIN_LENGTH and the digits-only filter must match the shared secret in
// `demo/.demo-password` (a 4-digit numeric code). If that secret is ever
// changed to a different length or to non-numeric characters, this screen can
// no longer express it — change both together.
const PIN_LENGTH = 4;

function PasswordGate({ onUnlock, t }) {
  const [pin, setPin] = useState('');
  const [status, setStatus] = useState('idle'); // idle | checking | denied
  const [focused, setFocused] = useState(true);
  const inputRef = useRef(null);
  // Guards against re-submitting the same completed PIN (the auto-submit
  // effect re-runs whenever `status` settles back to idle).
  const submittedRef = useRef('');

  const submit = async (code) => {
    if (code.length !== PIN_LENGTH || submittedRef.current === code) return;
    submittedRef.current = code;
    setStatus('checking');
    try {
      const ok = await verifyPassword(code);
      if (ok) {
        setPassword(code);        // persist for subsequent protected requests
        onUnlock();
        return;
      }
    } catch {
      // Network error reaching the backend — treated as denied, same copy.
    }
    setStatus('denied');
    // Clear the cells so the next attempt starts from empty underscores; the
    // shake plays on the still-filled cells for one animation frame first.
    setTimeout(() => {
      setPin('');
      submittedRef.current = '';
      if (inputRef.current) inputRef.current.focus();
    }, 450);
  };

  // Focus trap. The gate is the only thing on the page, so the caret must never
  // end up anywhere else: a click on any blank area, or any other element
  // stealing focus, puts it straight back on the PIN field, and typing works
  // immediately after the tab regains window focus. `pointerdown` is cancelled
  // rather than corrected afterwards, so focus never visibly leaves.
  useEffect(() => {
    const isSelf = (el) => el && el === inputRef.current;
    const refocus = () => {
      const el = inputRef.current;
      if (el && !el.disabled && document.activeElement !== el) el.focus();
    };
    const onPointerDown = (e) => {
      if (isSelf(e.target)) return;
      e.preventDefault();
      refocus();
    };
    const onFocusIn = (e) => { if (!isSelf(e.target)) refocus(); };
    document.addEventListener('pointerdown', onPointerDown);
    document.addEventListener('focusin', onFocusIn);
    window.addEventListener('focus', refocus);
    return () => {
      document.removeEventListener('pointerdown', onPointerDown);
      document.removeEventListener('focusin', onFocusIn);
      window.removeEventListener('focus', refocus);
    };
  }, []);

  // The input is `disabled` while a code is being checked, which drops focus.
  // Take it back the moment the check settles, so a rejected code can be
  // retyped without clicking anything.
  useEffect(() => {
    if (status !== 'checking' && inputRef.current) inputRef.current.focus();
  }, [status]);

  // Fires the check the moment the last digit lands — no button to press.
  const onChange = (e) => {
    const next = e.target.value.replace(/\D/g, '').slice(0, PIN_LENGTH);
    setPin(next);
    if (status === 'denied' && next.length < PIN_LENGTH) setStatus('idle');
    if (next.length === PIN_LENGTH) submit(next);
  };

  const busy = status === 'checking';
  const denied = status === 'denied';
  const cells = Array.from({ length: PIN_LENGTH }, (_, i) => pin[i] || '');
  // Index of the cell the caret sits on (only while focused and not full).
  const activeIdx = focused && !busy ? Math.min(pin.length, PIN_LENGTH - 1) : -1;

  return (
    <div style={{ maxWidth: 420, margin: '48px auto', textAlign: 'center' }}>
      <h2 style={{ fontSize: 24, fontWeight: 700, letterSpacing: '-0.02em', color: 'var(--color-text-primary)', marginBottom: 8 }}>
        {t('demo.gate.title')}
      </h2>
      <p style={{ fontSize: 14, color: 'var(--color-text-secondary)', lineHeight: 1.6, marginBottom: 28 }}>
        {t('demo.gate.prompt')}
      </p>

      {/* The cells are pure presentation; a single transparent input laid over
          them owns the value, so paste, backspace, autofill of an SMS-style
          one-time code and the mobile numeric keypad all work unchanged. */}
      <div
        className={denied ? 'pin-row pin-shake' : 'pin-row'}
        onClick={() => inputRef.current && inputRef.current.focus()}
        style={{
          position: 'relative', display: 'flex', justifyContent: 'center',
          gap: 14, marginBottom: 18, cursor: 'text',
        }}
      >
        {cells.map((d, i) => (
          <div
            key={i}
            style={{
              width: 54, height: 74, display: 'flex', flexDirection: 'column',
              alignItems: 'center', justifyContent: 'flex-end', userSelect: 'none',
            }}
          >
            <div
              style={{
                fontSize: 40, lineHeight: 1, fontWeight: 600, fontVariantNumeric: 'tabular-nums',
                color: denied ? C.redT : 'var(--color-text-primary,#222)',
                marginBottom: 12, opacity: d ? 1 : 0,
                transform: d ? 'translateY(0) scale(1)' : 'translateY(6px) scale(0.9)',
                transition: 'opacity 120ms ease-out, transform 120ms ease-out',
              }}
            >
              {d || '0'}
            </div>
            <div
              className={i === activeIdx && !d ? 'pin-bar pin-bar-active' : 'pin-bar'}
              style={{
                width: '100%', height: 5, borderRadius: 3,
                background: denied ? C.red : (d || i === activeIdx) ? 'var(--cobalt)' : 'var(--color-border-secondary)',
                transition: 'background 150ms ease-out',
              }}
            />
          </div>
        ))}
        <input
          ref={inputRef}
          type="text"
          inputMode="numeric"
          pattern="[0-9]*"
          autoComplete="one-time-code"
          maxLength={PIN_LENGTH}
          value={pin}
          autoFocus
          disabled={busy}
          onChange={onChange}
          onFocus={() => setFocused(true)}
          onBlur={() => setFocused(false)}
          aria-label={t('demo.gate.placeholder')}
          style={{
            position: 'absolute', inset: 0, width: '100%', height: '100%',
            opacity: 0, border: 'none', background: 'transparent',
            font: 'inherit', color: 'transparent', caretColor: 'transparent',
            cursor: 'text', outline: 'none',
          }}
        />
      </div>

      {/* Fixed-height status line so the cells do not jump between states. */}
      <div style={{ minHeight: 32, fontSize: 12.5, lineHeight: 1.5 }}>
        {busy && <span style={{ color: 'var(--color-text-secondary,#666)' }}>{t('demo.gate.checking')}</span>}
        {denied && <span style={{ color: C.redT }}>{t('demo.gate.denied')}</span>}
        {!busy && !denied && <span style={{ color: 'var(--color-text-tertiary,#999)' }}>{t('demo.gate.hint')}</span>}
      </div>
    </div>
  );
}

export default function Demo() {
  const { t, lang } = useLang();
  const [leftImg, setLeftImg] = useState(null);
  const [rightImg, setRightImg] = useState(null);
  const [running, setRunning] = useState(false);
  const [result, setResult] = useState(null);
  const [feedbackMode, setFeedbackMode] = useState(null); // 'confirm' | 'reject' | null
  const [correctedGrade, setCorrectedGrade] = useState(0);
  // The verdict standing on the CURRENT result, or null while it is unreviewed.
  // One result takes one verdict: while this is set the confirm/reject buttons
  // give way to "undo", so a prediction can neither be confirmed twice nor be
  // confirmed and rejected at the same time.
  // { verdict, correctedGrade, historyId, caseId, index }
  const [verdictEntry, setVerdictEntry] = useState(null);
  // The PDF hand-out is rendered on the server from the case as it stands, so
  // the button only reports progress and failure — there is nothing to cache.
  const [reportBusy, setReportBusy] = useState(false);
  const [reportError, setReportError] = useState('');
  const [toast, setToast] = useState('');
  // Relabeling buffer. Rebuilt from the verdicts in the case store on load (see
  // `refreshBuffer`), so it survives a reload the same way the study totals do
  // instead of emptying with the tab. A verdict given while the case store was
  // unreachable stays as a local row (`local: true`) until it can be filed.
  const [history, setHistory] = useState([]);
  // Tracks the active sample case (from WALKTHROUGH_POOL) so the result
  // panel can show pre-generated Grad-CAM + attention overlay. Any manual
  // upload or per-eye clear resets this to null — we cannot show heatmaps
  // for images that don't have a pre-generated companion under
  // `pipeline/dr0N/results/`.
  const [caseRef, setCaseRef] = useState(null);
  // Backend patient case (server/app/cases.py). `caseId` drives the UI; the ref
  // mirrors it for the upload chain below, which must read the freshly minted id
  // without waiting for a re-render.
  const [caseId, setCaseId] = useState(null);
  const caseIdRef = useRef(null);
  // Serialises case uploads: two eyes dropped in quick succession must join ONE
  // case, so the second call waits for the first to hand back the minted id
  // instead of racing it and opening a second directory.
  const caseChainRef = useRef(Promise.resolve());
  // Serialises verdict writes for the same reason: an undo clicked before the
  // save lands must retract the verdict that write produced, not race it.
  const verdictChainRef = useRef(Promise.resolve());
  // Store-wide counters for the statistics panel. They come from the case
  // directories on the server, so reloading (or moving to another machine)
  // does not reset them to zero.
  const [stats, setStats] = useState(null);
  const refreshStats = useCallback(() => {
    getCaseStats().then((s) => { if (s) setStats(s); }).catch(() => { /* offline */ });
  }, []);
  // Pull the relabeling buffer back from the case store. Rows the store already
  // holds replace their local counterparts; a row it never received (its writes
  // are best-effort) is kept, so a verdict is never silently dropped from the
  // buffer just because filing it failed.
  const refreshBuffer = useCallback(() => {
    getCaseVerdicts().then((payload) => {
      if (!payload || !Array.isArray(payload.entries)) return;
      const rows = payload.entries;
      const filed = new Set(rows.map(r => `${r.case_id}#${r.index}`));
      setHistory((prev) => {
        const unfiled = prev.filter(h => h.local && !filed.has(`${h.case_id}#${h.index}`));
        return [...rows, ...unfiled].sort((a, b) => (a.timestamp < b.timestamp ? 1 : -1));
      });
    }).catch(() => { /* offline */ });
  }, []);
  // Backend health. `health` is the /api/health payload (or null when the
  // backend is unreachable). `healthChecked` flips once the probe resolves.
  const [health, setHealth] = useState(null);
  const [healthChecked, setHealthChecked] = useState(false);
  // Collapsible "Additional info" block: the detailed per-image view (OD/fovea
  // centres & discs + step-by-step preprocessing stages). Collapsed by default.
  const [showDetail, setShowDetail] = useState(false);
  // Latches true the first time the block is opened. The heavy VisionWidget
  // (which fires a backend /visualize on mount) stays unmounted until then, so
  // simply loading an image does not trigger detector work; once opened it
  // stays mounted so re-collapsing/expanding animates without re-fetching.
  const [detailOpened, setDetailOpened] = useState(false);
  // Inside the detail block only one eye is shown at a time; a single chip in
  // the header toggles between them (like the Lite/Full and EN/ҚАЗ switches).
  // Defaults to the left eye (OS); the effect below falls back to whichever eye
  // is actually available when only one slot is filled.
  const [detailEye, setDetailEye] = useState('left');
  // Access gate (TASK-Demo §C.2/D). `authed` is true when the demo body is
  // unlocked: either the backend reports no password requirement / is offline
  // (the UI stays browsable; inference itself still needs a live backend), or
  // the user has supplied a valid password (revalidated from sessionStorage).
  const [authed, setAuthed] = useState(false);
  useEffect(() => {
    let alive = true;
    getHealth().then(async (h) => {
      if (!alive) return;
      setHealth(h);
      setHealthChecked(true);
      // No live gate to satisfy → unlock immediately (offline demo included).
      if (!h || !h.requires_password) { setAuthed(true); return; }
      // Gate active: try a previously stored password silently.
      const stored = getPassword();
      if (stored) {
        try { if (await verifyPassword(stored)) setAuthed(true); } catch { /* offline */ }
      }
    });
    return () => { alive = false; };
  }, []);
  // Both panels read the case store, which is behind the password gate, so they
  // are pulled once the demo is unlocked rather than on mount — a fetch fired
  // before the PIN is accepted comes back 401 and would leave the totals and the
  // buffer empty for the rest of the session.
  useEffect(() => {
    if (!authed) return;
    refreshStats();
    refreshBuffer();
  }, [authed, refreshStats, refreshBuffer]);
  // Real model is usable only when the backend is up AND a real checkpoint is
  // loaded (a boot without a checkpoint runs on random weights — meaningless).
  const apiReady = !!(health && health.checkpoint_loaded);
  // Preprocessing visualizations (/api/visualize, /api/gradcam) only need the
  // backend reachable — /api/visualize is checkpoint-free, so the "what the
  // model sees" widget lights up even before the model is trained.
  const liveVisuals = !!health;

  const eyes = useMemo(() => {
    const list = [];
    if (leftImg)  list.push({ eye: 'left',  src: leftImg.src,  name: leftImg.name  || 'left'  });
    if (rightImg) list.push({ eye: 'right', src: rightImg.src, name: rightImg.name || 'right' });
    return list;
  }, [leftImg, rightImg]);

  // Eyes that have a renderable detail widget: the slot has an image AND a
  // source of detail exists (ground-truth markers, or the live backend for the
  // detector path). Drives the per-eye switch in the "Additional info" block.
  const detailEyes = useMemo(() => {
    // Right eye (OD) first so its switch button sits on the left.
    const list = [];
    if (rightImg && (rightImg.gt || liveVisuals)) list.push('right');
    if (leftImg  && (leftImg.gt  || liveVisuals)) list.push('left');
    return list;
  }, [leftImg, rightImg, liveVisuals]);

  // Keep the selected detail eye valid: if it disappears (slot cleared / no
  // detail source) fall back to the first available eye, preferring right (OD).
  useEffect(() => {
    if (detailEyes.length && !detailEyes.includes(detailEye)) {
      setDetailEye(detailEyes[0]);
    }
  }, [detailEyes, detailEye]);

  // Close the current patient case. The next accepted image opens a fresh one —
  // a reset means a new patient, and their images must not land in the previous
  // patient's directory.
  const closeCase = () => {
    caseIdRef.current = null;
    setCaseId(null);
  };

  // File one image into the patient case, opening the case on the first accepted
  // image. An image the client-side check rejected as non-fundus is deliberately
  // not filed — the store holds patients, not stray files. Failures are silent:
  // persistence must never stand between the clinician and the model.
  const fileIntoCase = (img, eye) => {
    if (!img || !img.src) return;
    if (img.checks && img.checks.isFundus === false) return;
    const source = img.fromUpload === false ? 'sample' : 'upload';
    caseChainRef.current = caseChainRef.current
      .then(() => openCaseImage(img.src, eye, img.name, img.checks, caseIdRef.current, source))
      .then((res) => {
        if (res && res.case_id) {
          const opened = res.case_id !== caseIdRef.current;
          caseIdRef.current = res.case_id;
          setCaseId(res.case_id);
          if (opened) refreshStats();   // a new patient joined the store
        }
      })
      .catch(() => { /* best-effort */ });
  };

  // Drop the review state attached to the current result. Called wherever that
  // result itself goes stale (new run, new images, reset): a verdict belongs to
  // one prediction and must never carry over to the next.
  const clearReview = () => {
    setFeedbackMode(null);
    setVerdictEntry(null);
    setReportError('');
  };

  // Swap the two slots — used by the wrong-slot warning chip. Both images
  // (with their attached `checks`) move to the opposite slot; the laterality
  // check then re-evaluates against the new slot and the warning clears.
  const swapSlots = () => {
    const nextLeft = rightImg;
    const nextRight = leftImg;
    setLeftImg(nextLeft);
    setRightImg(nextRight);
    setResult(null);
    clearReview();
    // The swap corrects the laterality, so re-file both originals under their
    // new eyes — otherwise the case keeps each image on the wrong side.
    fileIntoCase(nextRight, 'right');
    fileIntoCase(nextLeft, 'left');
  };

  // Clear the workspace for the next patient. The buffer is deliberately not
  // touched: it is the study's verdict log now, read back from the case store,
  // so emptying it here would only hide rows that return on the next reload.
  const reset = () => {
    setLeftImg(null);
    setRightImg(null);
    setCaseRef(null);
    setResult(null);
    clearReview();
    setCorrectedGrade(0);
    closeCase();
  };

  const handleRun = async () => {
    if (eyes.length === 0) return;
    // No simulator fallback — inference requires a live backend with a loaded
    // checkpoint. If it is not ready, surface an error and stop.
    if (!apiReady) {
      setToast(t('demo.modelStatus.unavailable'));
      setTimeout(() => setToast(''), 5000);
      return;
    }
    setRunning(true);
    setResult(null);
    clearReview();
    try {
      // Let a just-dropped image finish opening its case, so the run is filed
      // into it rather than lost to a race with the upload.
      await caseChainRef.current;
      const r = await predictPatient(eyes, caseIdRef.current);
      setResult(normalizeApiResult(r, eyes));
    } catch (e) {
      console.error(e);
      setToast(t('demo.modelStatus.error'));
      setTimeout(() => setToast(''), 5000);
    } finally {
      setRunning(false);
    }
  };

  // Pick handler for an eye slot. On a manual upload we also try to match the
  // file against IDRiD localization ground truth by filename (IDRiD_NNN); if it
  // matches, we attach the `gt` payload so the preprocessing/centre overlay
  // renders for it (the overlay only shows for GT-backed images).
  const handlePick = (setImg, eye) => (img) => {
    setImg(img);
    fileIntoCase(img, eye);
    if (img && img.fromUpload) {
      setCaseRef(null);
      matchIdridUpload(img.name, img.src).then((gt) => {
        if (gt) setImg((cur) => (cur && cur.src === img.src ? { ...cur, gt } : cur));
      });
    }
  };

  // Roll a random IDRiD patient (one left + one right eye, colour-matched). The
  // left-anatomy image goes to the LEFT slot and the right-anatomy image to the
  // RIGHT slot. If the manifest is empty (prep script not yet run), fall back to
  // a walkthrough bilateral case.
  const loadRandomSample = () => {
    // A drawn sample is a different patient — close the case the previous images
    // belonged to so the new pair opens its own.
    closeCase();
    const patient = pickRandomIdridPatient();
    if (patient) {
      // Insert the random patient's images as PLAIN images — no ground-truth
      // payload. They are then detected, correctable, and classified exactly
      // like an uploaded snapshot (the detector finds OD/fovea, the clinician
      // can drag-correct, and DR is graded the same way). We deliberately drop
      // the IDRiD helper data (centres, FOV mask) so nothing is pre-supplied.
      const left = { src: process.env.PUBLIC_URL + '/' + patient.left.image, name: patient.left.id, fromUpload: false };
      const right = { src: process.env.PUBLIC_URL + '/' + patient.right.image, name: patient.right.id, fromUpload: false };
      setLeftImg(left);
      setRightImg(right);
      setCaseRef(null); // IDRiD samples have no pre-rendered explainability assets
      fileIntoCase(right, 'right');
      fileIntoCase(left, 'left');
    } else {
      const w = pickRandomWalkthrough(WALKTHROUGH_POOL);
      if (!w) return;
      const left = { src: process.env.PUBLIC_URL + '/' + w.left, name: w.left, fromUpload: false };
      const right = { src: process.env.PUBLIC_URL + '/' + w.right, name: w.right, fromUpload: false };
      setLeftImg(left);
      setRightImg(right);
      setCaseRef(w);
      fileIntoCase(right, 'right');
      fileIntoCase(left, 'left');
    }
    setResult(null);
    clearReview();
  };

  const submitFeedback = (verdict) => {
    // A result takes exactly one verdict: the buttons are replaced by "undo"
    // once it is given, and this guard closes the gap for a double click.
    if (!result || verdictEntry) return;
    const corrected = verdict === 'confirmed' ? result.pred : correctedGrade;
    const entry = {
      id: Date.now(),
      timestamp: new Date().toISOString(),
      case_id: caseIdRef.current || null,
      images: eyes.map(e => ({ eye: e.eye, source: e.name })),
      predicted: result.pred,
      confidence: Number(result.confidence.toFixed(4)),
      probs: result.probs.map(p => Number(p.toFixed(4))),
      verdict,
      corrected_grade: corrected,
      latency_ms: result.latencyMs,
      model: 'config-D (pipeline + EfficientNet-B3)',
      // Local until the case store confirms it. `refreshBuffer` replaces a filed
      // row with the store's copy and keeps an unfiled one.
      local: true,
    };
    setHistory(h => [entry, ...h]);
    setVerdictEntry({
      verdict, correctedGrade: corrected, historyId: entry.id,
      caseId: caseIdRef.current, index: 0,
    });
    setFeedbackMode(null);
    setToast(t('demo.thanks'));
    setTimeout(() => setToast(''), 2500);

    // Durable copy: the verdict is what the case store exists for. The local
    // buffer above is kept either way — it is what the Export button reads.
    // The index that comes back is the one an undo withdraws.
    verdictChainRef.current = verdictChainRef.current
      .then(() => submitCaseFeedback(caseIdRef.current, {
        verdict,
        correctedGrade: corrected,
        predictedGrade: result.pred,
        confidence: result.confidence,
      }))
      .then((saved) => {
        if (saved && saved.index) {
          setVerdictEntry(v => (v && v.historyId === entry.id ? { ...v, index: saved.index } : v));
          // Stamp the store's ordinal onto the local row so the refresh below
          // recognises it as filed and swaps in the store's own copy.
          setHistory(h => h.map(x => (x.id === entry.id ? { ...x, index: saved.index } : x)));
        }
        refreshStats();
        refreshBuffer();
      })
      .catch(() => { /* best-effort */ });
  };

  // Take a verdict back: the buttons return, the buffer row goes, and the
  // verdict is withdrawn from the case on the server — an undone verdict must
  // leave nothing behind to be counted in the statistics or exported as a label.
  // Queued behind the save so an immediate undo retracts the verdict that save
  // wrote; with no index yet, the server withdraws the case's latest, which is
  // the one just written.
  const undoVerdict = () => {
    const given = verdictEntry;
    if (!given) return;
    setVerdictEntry(null);
    setFeedbackMode(null);
    setCorrectedGrade(0);
    // Drop the row by its local id, and by its position in the store as well —
    // once `refreshBuffer` has swapped in the store's copy the local id is gone.
    setHistory(h => h.filter(x => (
      x.id !== given.historyId
      && !(given.caseId && given.index && x.case_id === given.caseId && x.index === given.index)
    )));
    if (!given.caseId) return;
    verdictChainRef.current = verdictChainRef.current
      .then(() => retractCaseFeedback(given.caseId, given.index || undefined))
      .then(() => { refreshStats(); refreshBuffer(); })
      .catch(() => { /* best-effort */ });
  };

  // Save a blob under `filename` through a throwaway anchor. Shared by the
  // JSONL export and the PDF report.
  const saveBlob = (blob, filename) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Download the patient's full PDF report: verdict, prediction, the images,
  // every preprocessing stage and the attention maps, rendered by the server
  // from the case on disk.
  //
  // Queued behind the verdict chain on purpose. The verdict is written
  // asynchronously, so a report requested the instant the reviewer clicks
  // confirm/reject would otherwise race that write and come back describing an
  // unreviewed case. Waiting also means an undo-then-download reports the case
  // as it actually stands.
  const downloadReport = () => {
    const cid = caseIdRef.current;
    if (!cid || reportBusy) return;
    setReportBusy(true);
    setReportError('');
    verdictChainRef.current = verdictChainRef.current
      .then(() => fetchCaseReport(cid, lang))
      .then(({ blob, filename }) => {
        saveBlob(blob, filename);
        setReportBusy(false);
      })
      .catch((err) => {
        setReportBusy(false);
        setReportError(err && err.message ? err.message : String(err));
      });
  };

  const exportJsonl = () => {
    if (history.length === 0) return;
    // `local` is bookkeeping for the reconciliation above, not part of the label.
    const jsonl = history
      .map(({ local, ...row }) => JSON.stringify(row))
      .join('\n');
    saveBlob(
      new Blob([jsonl], { type: 'application/x-ndjson' }),
      `dr-relabel-${new Date().toISOString().replace(/[:.]/g, '-')}.jsonl`,
    );
  };

  // Block the demo body behind the access screen only when the backend
  // actively requires a password and we are not yet authenticated. A null/
  // offline health never gates — the UI stays browsable without a backend.
  if (healthChecked && health && health.requires_password && !authed) {
    return <PasswordGate onUnlock={() => setAuthed(true)} t={t} />;
  }

  return (
    <div>
      {/* Header */}
      <header style={{ marginBottom: 30 }}>
        <h2 style={{
          fontSize: 30, fontWeight: 700, letterSpacing: '-0.025em', lineHeight: 1.12,
          color: 'var(--color-text-primary)', margin: '0 0 10px 0', maxWidth: '26ch',
        }}>
          {t('demo.title')}
        </h2>
        <p style={{ fontSize: 14, color: 'var(--color-text-secondary)', margin: '0 0 18px 0', lineHeight: 1.6, maxWidth: '64ch' }}>
          {t('demo.subtitle')}
        </p>
        {/* Framing block (TASK-Demo D.1) — muted, no marketing copy. The two
            text lines form a column on the left, the random-sample button sits
            on the right; when the row gets tight the button yields width first. */}
        <div style={{
          fontSize: 12, color: 'var(--color-text-secondary)', lineHeight: 1.55,
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          gap: 16, flexWrap: 'wrap',
          padding: '12px 14px 12px 16px', background: 'var(--color-background-primary)',
          border: '1px solid var(--color-border-tertiary)', borderRadius: 10,
        }}>
          <div style={{ flex: '1 1 320px', minWidth: 0 }}>
            <div style={{ fontWeight: 600, color: 'var(--color-text-primary)' }}>{t('demo.framing.line1')}</div>
            <div>{t('demo.framing.line2')}</div>
          </div>
          <button onClick={loadRandomSample} title={t('demo.randomHint')} className="btn btn-quiet btn-wrap" style={{ flexShrink: 1 }}>
            {/* Shuffle glyph — a quiet "draw a sample" cue in place of the dice emoji. */}
            <svg
              width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor"
              strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"
              style={{ flexShrink: 0 }}
            >
              <path d="M16 3h5v5" />
              <path d="M4 20 21 3" />
              <path d="M21 16v5h-5" />
              <path d="m15 15 6 6" />
              <path d="m4 4 5 5" />
            </svg>
            {t('demo.random')}
          </button>
        </div>
      </header>

      {/* Upload section */}
      <Sec step={1} title={t('demo.uploadSection')}>
        {/* Right eye (OD) shown on the LEFT, left eye (OS) on the RIGHT — matches
            the clinical convention for displaying fundus pairs. */}
        <div className="eye-slot-row" style={{ display: 'flex', gap: 20, flexWrap: 'wrap' }}>
          <EyeSlot
            label={t('demo.rightEye')}
            eye="right"
            image={rightImg}
            onPick={handlePick(setRightImg, 'right')}
            onClear={() => { setRightImg(null); setCaseRef(null); setResult(null); clearReview(); }}
            onSwap={swapSlots}
            t={t}
          />
          <EyeSlot
            label={t('demo.leftEye')}
            eye="left"
            image={leftImg}
            onPick={handlePick(setLeftImg, 'left')}
            onClear={() => { setLeftImg(null); setCaseRef(null); setResult(null); clearReview(); }}
            onSwap={swapSlots}
            t={t}
          />
        </div>

        {/* Additional info: a collapsible block revealing the detailed per-image
            view — OD/fovea centres & discs the detector found, plus the result
            of each preprocessing stage as its own slide (TASK-Demo D.2). Shown
            once at least one slot has an image and a source of detail exists
            (ground-truth markers, or the live backend for the detector path). */}
        {(leftImg || rightImg) && (liveVisuals || leftImg?.gt || rightImg?.gt) && (() => {
          // One eye at a time, picked by the switch below (defaults to right).
          // The chosen slot is rendered with GT markers when it has them,
          // otherwise via the live detector path. Computed unconditionally so
          // the panel's contents stay mounted across the open/close animation.
          const selected = detailEyes.includes(detailEye) ? detailEye : detailEyes[0];
          const img = selected === 'left' ? leftImg : rightImg;
          const toggle = () => setShowDetail((v) => { if (!v) setDetailOpened(true); return !v; });
          return (
            <div style={{ marginTop: 12 }}>
              {/* Accordion header row. Doubles as the top of the panel when
                  open: the bottom corners square off to fuse with the body
                  below. The clickable title (left) toggles the panel; the eye
                  switch (right) is a sibling button — not nested — so clicking
                  it never toggles the panel. */}
              <div style={{
                display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap',
                padding: '8px 12px',
                background: 'var(--color-background-primary)',
                border: '1px solid var(--color-border-tertiary)',
                borderRadius: showDetail ? '10px 10px 0 0' : 10,
                transition: 'border-radius 0.25s ease',
              }}>
                <button
                  type="button"
                  onClick={toggle}
                  aria-expanded={showDetail}
                  style={{
                    display: 'flex', alignItems: 'center', gap: 8,
                    flex: 1, minWidth: 0, padding: '2px 0',
                    fontSize: 13, fontWeight: 600, textAlign: 'left',
                    background: 'transparent', color: 'var(--cobalt)',
                    border: 'none', cursor: 'pointer',
                  }}
                >
                  <span style={{
                    fontSize: 11, display: 'inline-block', lineHeight: 1, flexShrink: 0,
                    transform: showDetail ? 'rotate(90deg)' : 'rotate(0deg)',
                    transition: 'transform 0.25s ease',
                  }}>▸</span>
                  {t('demo.vision.additionalInfo')}
                </button>

                {/* Single eye switch (merged from the old two buttons). Shows
                    the active eye and flips to the other on click — same chip
                    pattern as Lite/Full and EN/ҚАЗ. Disabled (label only) when
                    just one eye is loaded, since there is nothing to switch to. */}
                {detailEyes.length > 0 && (() => {
                  const dual = detailEyes.length > 1;
                  return (
                    <button
                      type="button"
                      className="chip-toggle"
                      disabled={!dual}
                      onClick={() => setDetailEye(selected === 'left' ? 'right' : 'left')}
                      title={dual
                        ? `${selected === 'left' ? t('demo.leftEye') : t('demo.rightEye')} — ${t('demo.vision.additionalInfo')}`
                        : (selected === 'left' ? t('demo.leftEye') : t('demo.rightEye'))}
                      style={{ flexShrink: 0, cursor: dual ? 'pointer' : 'default', opacity: dual ? 1 : 0.7 }}
                    >
                      <span>{selected === 'left' ? 'OS' : 'OD'}</span>
                      <span className="chip-key">{t('demo.eye.' + selected)}</span>
                    </button>
                  );
                })()}
              </div>

              {/* Smoothly expanding body: the grid-template-rows 0fr→1fr trick
                  animates height without measuring. Holds the full VisionWidget
                  for the eye selected in the header — analysis-space input,
                  OD·fovea markers, FOV-mask toggle, the step-by-step
                  preprocessing-stage slides. */}
              <div
                aria-hidden={!showDetail}
                style={{
                  display: 'grid',
                  gridTemplateRows: showDetail ? '1fr' : '0fr',
                  transition: 'grid-template-rows 0.3s ease',
                  border: `1px solid ${showDetail ? 'var(--color-border-tertiary)' : 'transparent'}`,
                  borderTop: 'none', borderRadius: '0 0 10px 10px',
                  background: showDetail ? 'var(--color-background-primary)' : 'transparent',
                }}
              >
                <div style={{ overflow: 'hidden', minHeight: 0 }}>
                  <div style={{
                    padding: 10,
                    pointerEvents: showDetail ? 'auto' : 'none',
                  }}>
                    {/* Selected eye's detailed view — GT-backed (markers + mask
                        render even offline) or the live detector path (learned
                        OD/fovea overlay, drag-correctable centres, stage slides).
                        Mounted only after the panel has been opened once, then
                        kept alive so toggling stays smooth and refetch-free. */}
                    {img && detailOpened && (
                      <VisionWidget
                        key={selected}
                        src={img.src}
                        eye={selected}
                        name={img.name}
                        enabled={liveVisuals}
                        gt={img.gt}
                        caseId={caseId}
                        t={t}
                      />
                    )}
                  </div>
                </div>
              </div>
            </div>
          );
        })()}

      </Sec>

      {/* Run section */}
      <Sec step={2} title={t('demo.runSection')}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' }}>
          <button
            onClick={handleRun}
            disabled={running || eyes.length === 0}
            className="btn btn-primary"
            style={{ minHeight: 42, padding: '0 22px', fontSize: 14 }}
          >
            {running ? t('demo.running') : t('demo.runButton')}
          </button>
          {eyes.length === 0 && (
            <span style={{ fontSize: 12.5, color: 'var(--color-text-secondary)' }}>{t('demo.needAtLeastOne')}</span>
          )}
          {eyes.length > 0 && !running && (
            <span style={{ fontSize: 12.5, color: 'var(--color-text-secondary)' }}>
              {eyes.length} {eyes.length === 1 ? t('demo.image') : t('demo.images')}
            </span>
          )}
        </div>
      </Sec>

      {/* Result section */}
      {result && (
        <Sec step={3} title={t('demo.resultSection')}>
          <div className="panel">
            <div className="result-head">
              <div>
                <div className="result-kicker">{t('demo.patientGrade')}</div>
                <div className="result-grade" style={{ color: GRADE_INK[result.pred] }}>
                  {gradeName(t, result.pred)}
                </div>
                <div className="result-kicker" style={{ marginBottom: 14 }}>
                  {t('demo.gradeOf').replace('{g}', result.pred)}
                </div>
                <span className="referral" style={result.pred >= 2
                  ? { background: C.coralBg, color: GRADE_INK[3] }
                  : { background: C.tealBg, color: GRADE_INK[0] }}>
                  {result.pred >= 2 ? t('demo.referYes') : t('demo.referNo')}
                </span>
              </div>
              <div>
                <div className="result-kicker" style={{ marginBottom: 22 }}>{t('demo.scale.title')}</div>
                <GradeScale probs={result.probs} pred={result.pred} t={t} />
              </div>
            </div>
            <div className="facts">
              <div className="fact">
                <div className="fact-k">{t('demo.confidence')}</div>
                <div className="fact-v">{(result.confidence * 100).toFixed(1)}%</div>
              </div>
              <div className="fact">
                <div className="fact-k">{t('demo.latency')}</div>
                <div className="fact-v">{result.latencyMs} ms</div>
              </div>
              {/* Per-eye breakdown: the patient grade above is the worse eye. */}
              {result.perEye.length > 1 && result.perEye.map((eye, i) => (
                <div key={i} className="fact">
                  <div className="fact-k">{t('demo.eye.' + (eye.eye === 'left' ? 'left' : 'right'))} ({eye.eye === 'left' ? 'OS' : 'OD'})</div>
                  <div className="fact-v" style={{ color: GRADE_INK[eye.result.pred] }}>
                    {t('demo.gradeShort.' + eye.result.pred)}
                  </div>
                  <div className="fact-s">{(eye.result.confidence * 100).toFixed(1)}%, {eye.result.latencyMs} ms</div>
                </div>
              ))}
            </div>
          </div>

          {/* Grad-CAM heatmap + attention overlay.
              Live (from the checkpoint) for custom uploads when the real model
              is active; pre-rendered walkthrough assets otherwise. */}
          {apiReady && caseRef === null && eyes.length > 0 ? (
            <LiveVisualizationBlock eyes={eyes} caseId={caseId} t={t} />
          ) : (
            <VisualizationBlock
              caseRef={caseRef}
              leftPresent={!!leftImg}
              rightPresent={!!rightImg}
              t={t}
            />
          )}
        </Sec>
      )}

      {/* Feedback section */}
      {result && (
        <Sec step={4} title={t('demo.feedbackSection')} note={t('demo.feedbackHint')}>
          {/* One verdict per prediction. Until it is given, the two buttons; once
              it is, they give way to the standing verdict and a single "undo",
              so the same result cannot be confirmed twice — or confirmed and
              rejected at once. */}
          {verdictEntry ? (
            <div style={{
              display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'center',
              padding: '14px 16px', borderRadius: 12,
              background: 'var(--color-background-primary)',
              border: '1px solid var(--color-border-tertiary)',
              boxShadow: `inset 4px 0 0 ${verdictEntry.verdict === 'confirmed' ? GRADE_COLORS[0] : GRADE_COLORS[4]}`,
            }}>
              <div style={{ flex: 1, minWidth: 180 }}>
                <div style={{
                  fontSize: 14, fontWeight: 600,
                  color: verdictEntry.verdict === 'confirmed' ? GRADE_INK[0] : GRADE_INK[4],
                }}>
                  {verdictEntry.verdict === 'confirmed' ? '✓' : '✕'}{' '}
                  {t('demo.verdictGiven.' + verdictEntry.verdict)}
                </div>
                <div style={{ fontSize: 12.5, color: 'var(--color-text-secondary)', marginTop: 3 }}>
                  {t('demo.recordedGrade')}: <strong>{t('demo.grade.' + verdictEntry.correctedGrade)}</strong>
                </div>
              </div>
              {/* The verdict closes the review, so this is where the patient's
                  report becomes downloadable. It needs a server-side case: with
                  no backend there are no stage images or attention maps to put
                  in it. */}
              {caseId && (
                <button
                  onClick={downloadReport}
                  disabled={reportBusy}
                  title={t('demo.report.hint')}
                  className="btn btn-primary"
                  style={{ cursor: reportBusy ? 'wait' : 'pointer' }}
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                    <path d="M12 3v12" /><path d="m7 10 5 5 5-5" /><path d="M5 21h14" />
                  </svg>
                  {reportBusy ? t('demo.report.busy') : t('demo.report.download')}
                </button>
              )}
              <button onClick={undoVerdict} className="btn btn-quiet">
                {t('demo.undoVerdict')}
              </button>
            </div>
          ) : (
            <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', alignItems: 'center' }}>
              <button
                onClick={() => { setFeedbackMode('confirm'); submitFeedback('confirmed'); }}
                className="btn btn-confirm"
              >
                {t('demo.confirm')}
              </button>
              <button onClick={() => setFeedbackMode('reject')} className="btn btn-reject">
                {t('demo.reject')}
              </button>
            </div>
          )}
          {!verdictEntry && feedbackMode === 'reject' && (
            <div style={{
              marginTop: 12, padding: '12px 14px', borderRadius: 10,
              background: 'var(--color-background-primary)', border: '1px solid var(--color-border-tertiary)',
              boxShadow: `inset 4px 0 0 ${GRADE_COLORS[4]}`,
              display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap',
            }}>
              <label htmlFor="corrected-grade" style={{ fontSize: 13, fontWeight: 600 }}>
                {t('demo.correctGrade')}:
              </label>
              <select
                id="corrected-grade"
                value={correctedGrade}
                onChange={(e) => setCorrectedGrade(parseInt(e.target.value, 10))}
                style={{ minHeight: 36, padding: '0 10px', fontSize: 13, border: '1px solid var(--color-border-secondary)', borderRadius: 8, background: '#fff' }}
              >
                {[0, 1, 2, 3, 4].map(g => (
                  <option key={g} value={g}>{t('demo.grade.' + g)}</option>
                ))}
              </select>
              <button onClick={() => submitFeedback('rejected')} className="btn btn-primary">
                {t('demo.submit')}
              </button>
            </div>
          )}
          {reportError && (
            <div style={{
              marginTop: 10, padding: '8px 12px', borderRadius: 6,
              background: C.redBg, color: C.redT, fontSize: 11, fontWeight: 600,
            }}>
              ✕ {t('demo.report.failed')} — {reportError}
            </div>
          )}
          {toast && (
            <div style={{
              marginTop: 10, padding: '8px 12px', borderRadius: 6,
              background: C.greenBg, color: C.greenT, fontSize: 11, fontWeight: 600,
            }}>
              ✓ {toast}
            </div>
          )}
          {/* Where this patient's artifacts live on the server. Shown only when a
              case was actually opened (backend reachable, images accepted). */}
          {caseId && (
            <div style={{ fontSize: 10, color: 'var(--color-text-secondary,#777)', marginTop: 10, lineHeight: 1.5 }}>
              {t('demo.case.stored').replace('{id}', caseId)}
            </div>
          )}
        </Sec>
      )}

      {/* History / relabeling buffer */}
      <Sec title={`${t('demo.historyTitle')} (${history.length})`}>
        <div style={{ display: 'flex', gap: 8, marginBottom: 10 }}>
          <button onClick={exportJsonl} disabled={history.length === 0} className="btn btn-quiet btn-sm">
            {t('demo.export')}
          </button>
        </div>
        {/* The buffer is no longer this tab's scratch list, so say where the rows
            come from — and that a row is withdrawn one verdict at a time (Undo
            on the result), never by wiping the block. */}
        <div style={{ fontSize: 12, color: 'var(--color-text-secondary)', marginBottom: 10, maxWidth: '70ch' }}>
          {t('demo.historySource')}
        </div>
        {history.length === 0 ? (
          <Note>{t('demo.historyEmpty')}</Note>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11 }}>
              <thead>
                <tr style={{ borderBottom: '1.5px solid var(--color-text-primary)', color: 'var(--color-text-secondary)', fontSize: 11 }}>
                  <th style={{ padding: '5px 8px', textAlign: 'left', fontWeight: 600 }}>{t('demo.col.time')}</th>
                  <th style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>{t('demo.col.images')}</th>
                  <th style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>{t('demo.col.predicted')}</th>
                  <th style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>{t('demo.col.verdict')}</th>
                  <th style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>{t('demo.col.corrected')}</th>
                </tr>
              </thead>
              <tbody>
                {history.map(h => (
                  <tr key={h.id} style={{ borderBottom: '1px solid var(--color-border-tertiary,#eee)' }}>
                    <td style={{ padding: '6px 8px', color: 'var(--color-text-secondary)' }}>
                      {new Date(h.timestamp).toLocaleTimeString()}
                    </td>
                    <td style={{ padding: '5px 8px', textAlign: 'center' }}>{h.images.length}</td>
                    <td style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>
                      {t('demo.gradeShort.' + h.predicted)} ({(h.confidence * 100).toFixed(0)}%)
                    </td>
                    <td style={{ padding: '5px 8px', textAlign: 'center' }}>
                      <span style={{
                        padding: '2px 8px', borderRadius: 999, fontSize: 11, fontWeight: 600,
                        background: h.verdict === 'confirmed' ? C.tealBg : C.redBg,
                        color: h.verdict === 'confirmed' ? GRADE_INK[0] : GRADE_INK[4],
                      }}>
                        {t('demo.verdict.' + h.verdict)}
                      </span>
                    </td>
                    <td style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>
                      {t('demo.gradeShort.' + h.corrected_grade)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* Store-wide statistics. The buffer above is this session's work and is
            cleared with it; these numbers come from the server and stay. */}
        <CaseStatsPanel stats={stats} t={t} />
      </Sec>

      {/* Provenance string (TASK-Demo D.7) — what the committee can quote. */}
      {health && (
        <div style={{ fontSize: 11, color: 'var(--color-text-tertiary)', marginTop: 4 }}>
          version {health.version} · git {health.git_sha || 'n/a'} · checkpoint {health.checkpoint}
          {health.checkpoint_loaded ? '' : ' (not loaded)'} · {health.device}
        </div>
      )}

      <div style={{ marginTop: 14 }}>
        <button onClick={() => reset()} className="btn btn-quiet btn-sm">
          Reset case
        </button>
      </div>
    </div>
  );
}
