// src/tabs/Demo.js — Live inference demo page.
// Lets the user supply up to two fundus images (left + right eye) of one
// patient, runs the trained model on the backend, and lets the user confirm or
// reject the result. Confirmed / corrected cases are appended to a local
// relabeling buffer that can be exported as JSONL for further training.

import { useEffect, useMemo, useRef, useState } from 'react';
import { C } from '../data';
import { Sec, Note } from '../components';
import { useLang } from '../i18n';
import { IDRID_PATIENTS } from './_idridSamples';
import { matchIdridUpload } from './_idridUpload';
import { analyzeFundus } from './_analyzeFundus';
import { predictPatient, getHealth, getPassword, setPassword, verifyPassword } from './_apiPredict';
import VisionWidget from './_VisionWidget';
import LiveVisualizationBlock from './_LiveGradcam';

// ---------------------------------------------------------------------------
// Walk-through cases that share an image with the preprocessing-pipeline
// gallery. Each entry exposes pre-generated Grad-CAM heatmap + attention
// overlay rendered by `demo/web/public/pipeline/helpers/s8_results.py` (proxy
// heatmap derived from flat-field anomaly detection; not a real Grad-CAM
// from a trained checkpoint).
// ---------------------------------------------------------------------------
const WALKTHROUGH_POOL = [
  { id: 'walk_dr00', grade: 0, left: 'pipeline/dr00/input/left.png', right: 'pipeline/dr00/input/right.png', explainable: true, resultsBase: 'pipeline/dr00/results' },
  { id: 'walk_dr01', grade: 1, left: 'pipeline/dr01/input/left.png', right: 'pipeline/dr01/input/right.png', explainable: true, resultsBase: 'pipeline/dr01/results' },
  { id: 'walk_dr02', grade: 2, left: 'pipeline/dr02/input/left.png', right: 'pipeline/dr02/input/right.png', explainable: true, resultsBase: 'pipeline/dr02/results' },
  { id: 'walk_dr03', grade: 3, left: 'pipeline/dr03/input/left.png', right: 'pipeline/dr03/input/right.png', explainable: true, resultsBase: 'pipeline/dr03/results' },
  { id: 'walk_dr04', grade: 4, left: 'pipeline/dr04/input/left.png', right: 'pipeline/dr04/input/right.png', explainable: true, resultsBase: 'pipeline/dr04/results' },
];

// ---------------------------------------------------------------------------
// IDRiD image pool for the Random button, sourced from `_idridSamples.js`
// (regenerated by `demo/web/scripts/prepare_idrid_samples.py`).
//
// IDRiD is monocular, so each entry is a SYNTHETIC bilateral patient: one
// left-eye + one right-eye image of the same DR grade (laterality derived from
// anatomy — fovea temporal to disc). The Random button inserts these images as
// PLAIN samples (no ground-truth payload): they are detected, drag-correctable,
// and DR-graded exactly like an uploaded snapshot — the IDRiD localization
// helper data (OD/fovea centres, FOV mask) is intentionally not supplied.
// ---------------------------------------------------------------------------
let lastIdridIdx = -1;
function pickRandomIdridPatient() {
  if (!IDRID_PATIENTS || IDRID_PATIENTS.length === 0) return null;
  let idx;
  do {
    idx = Math.floor(Math.random() * IDRID_PATIENTS.length);
  } while (IDRID_PATIENTS.length > 1 && idx === lastIdridIdx);
  lastIdridIdx = idx;
  return IDRID_PATIENTS[idx];
}

// Walkthrough fallback (used only when IDRID_PATIENTS is empty).
let lastWalkIdx = -1;
function pickRandomWalkthrough(pool) {
  if (!pool || pool.length === 0) return null;
  let idx;
  do {
    idx = Math.floor(Math.random() * pool.length);
  } while (pool.length > 1 && idx === lastWalkIdx);
  lastWalkIdx = idx;
  return pool[idx];
}

// ---------------------------------------------------------------------------
// Normalize the backend's PatientPredictionResponse (snake_case, no per-eye
// src) into the shape the Result panel renders: { pred, probs, confidence,
// latencyMs, perEye: [{ eye, src, result }] }.
// ---------------------------------------------------------------------------
function normalizeApiResult(r, eyes) {
  return {
    pred: r.pred,
    probs: r.probs,
    confidence: r.confidence,
    latencyMs: r.latency_ms,
    perEye: (r.per_eye || []).map(p => ({
      eye: p.eye,
      src: (eyes.find(e => e.eye === p.eye) || {}).src,
      result: {
        pred: p.pred,
        probs: p.probs,
        confidence: p.confidence,
        latencyMs: p.latency_ms,
      },
    })),
  };
}

// ---------------------------------------------------------------------------
// UI sub-components
// ---------------------------------------------------------------------------
function EyeSlot({ label, eye, image, onPick, onClear, onSwap, t }) {
  const inputRef = useRef(null);
  const [dims, setDims] = useState(null);
  // "Keep" dismisses the wrong-slot warning for the current image only.
  const [dismissed, setDismissed] = useState(false);
  // Reset the size badge and dismissed-warning state when the loaded image
  // changes (or is cleared) so we never carry the previous image's dimensions
  // or a stale dismissal into a freshly loaded image. (Extracted to a variable
  // so react-hooks/exhaustive-deps can statically check it — a bare
  // `image && image.src` in the deps array trips the CI build under CI=1.)
  const imageSrc = image && image.src;
  useEffect(() => { setDims(null); setDismissed(false); }, [imageSrc]);

  const onChange = (e) => {
    const file = e.target.files && e.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = async (ev) => {
      const checks = await analyzeFundus(ev.target.result);
      onPick({ src: ev.target.result, name: file.name, fromUpload: true, checks });
    };
    reader.readAsDataURL(file);
  };
  const onDrop = (e) => {
    e.preventDefault();
    const file = e.dataTransfer.files && e.dataTransfer.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = async (ev) => {
      const checks = await analyzeFundus(ev.target.result);
      onPick({ src: ev.target.result, name: file.name, fromUpload: true, checks });
    };
    reader.readAsDataURL(file);
  };

  // Derived check state for the chips below the preview.
  const checks = image && image.checks;
  const showNotFundus = !!(checks && checks.isFundus === false);
  const showWrongSide = !!(
    checks && checks.laterality && checks.laterality !== eye &&
    checks.confidence > 0.5 && !dismissed
  );
  const wrongSideMsg = showWrongSide
    ? t('demo.check.wrongSide').replace('{eye}', t('demo.check.eye.' + checks.laterality))
    : '';

  return (
    <div style={{ flex: 1, minWidth: 220 }}>
      <div style={{
        display: 'flex', alignItems: 'baseline', justifyContent: 'space-between',
        marginBottom: 6, gap: 6,
      }}>
        <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-text-secondary,#666)' }}>
          {label}
        </div>
        {dims && (
          <div style={{
            fontSize: 9, fontFamily: 'monospace',
            color: 'var(--color-text-secondary,#888)',
          }}>
            {dims.w} × {dims.h} px
          </div>
        )}
      </div>
      <div
        onClick={() => inputRef.current && inputRef.current.click()}
        onDragOver={(e) => e.preventDefault()}
        onDrop={onDrop}
        style={{
          width: '100%',
          // Fixed 1:1 frame regardless of image presence — keeps the form
          // height stable so siblings (Run button, Result panel) don't jump
          // when an image loads or is cleared. Image is letterboxed inside.
          aspectRatio: '1 / 1',
          border: `1px dashed ${image ? C.teal : 'var(--color-border-secondary,#ccc)'}`,
          borderRadius: 10,
          // Keep the letterbox grey (not black) even with an image loaded: fundus
          // photos carry their own black border, so a black box would blend with
          // it and make the snapshot look smaller than it is. Grey reveals the
          // true image rectangle and shape.
          background: 'var(--color-background-secondary,#f7f7f5)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          cursor: 'pointer', overflow: 'hidden', position: 'relative',
        }}
      >
        {image ? (
          <img
            src={image.src}
            alt={label}
            onLoad={(e) => setDims({ w: e.target.naturalWidth, h: e.target.naturalHeight })}
            style={{
              width: '100%', height: '100%',
              objectFit: 'contain', display: 'block',
            }}
          />
        ) : (
          <div style={{ textAlign: 'center', color: 'var(--color-text-secondary,#888)', padding: 12 }}>
            <div style={{ fontSize: 11, fontWeight: 600 }}>{t('demo.dropHere')}</div>
            <div style={{ fontSize: 9, marginTop: 4 }}>{t('demo.formats')}</div>
          </div>
        )}
        <input ref={inputRef} type="file" accept="image/*" onChange={onChange} style={{ display: 'none' }} />
      </div>

      {/* Validation chips (uploaded images only). Warn, never block. */}
      {showNotFundus && (
        <div style={{
          marginTop: 6, padding: '4px 8px', borderRadius: 4, fontSize: 10,
          background: C.amberBg, color: C.amberT, border: `1px solid ${C.amber}`,
        }}>
          ⚠ {t('demo.check.notFundus')}
        </div>
      )}
      {showWrongSide && (
        <div style={{
          marginTop: 6, padding: '6px 8px', borderRadius: 4, fontSize: 10,
          background: C.redBg, color: C.redT, border: `1px solid ${C.red}`,
          display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap',
        }}>
          <span style={{ flex: 1, minWidth: 120 }}>⚠ {wrongSideMsg}</span>
          <button
            onClick={onSwap}
            style={{
              padding: '2px 8px', fontSize: 10, fontWeight: 600,
              background: C.red, color: 'white', border: 'none',
              borderRadius: 3, cursor: 'pointer',
            }}
          >
            {t('demo.check.swap')}
          </button>
          <button
            onClick={() => setDismissed(true)}
            style={{
              padding: '2px 8px', fontSize: 10,
              background: 'transparent', color: C.redT,
              border: `1px solid ${C.red}`, borderRadius: 3, cursor: 'pointer',
            }}
          >
            {t('demo.check.keep')}
          </button>
        </div>
      )}
      {/* Always reserve the Clear button's vertical space so the form height
          doesn't change when an image is added/removed. The button is only
          visible (and clickable) when there is something to clear. */}
      <button
        onClick={onClear}
        disabled={!image}
        style={{
          marginTop: 6, fontSize: 10, padding: '3px 8px', background: 'transparent',
          color: C.red, border: `1px solid ${C.red}`, borderRadius: 4,
          cursor: image ? 'pointer' : 'default',
          visibility: image ? 'visible' : 'hidden',
        }}
      >
        {t('demo.clear')}
      </button>
    </div>
  );
}

function ProbabilityBar({ idx, p, isPred, t }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
      <div style={{ fontSize: 10, color: 'var(--color-text-secondary,#666)', minWidth: 36, fontWeight: isPred ? 700 : 400 }}>
        {t('demo.gradeShort.' + idx)}
      </div>
      <div style={{ flex: 1, height: 16, background: 'var(--color-background-secondary,#eeede9)', borderRadius: 3, position: 'relative', overflow: 'hidden' }}>
        <div style={{ width: `${p * 100}%`, height: '100%', background: isPred ? C.teal : C.gray, opacity: isPred ? 0.85 : 0.45 }} />
        <span style={{ position: 'absolute', right: 5, top: '50%', transform: 'translateY(-50%)', fontSize: 9, fontWeight: isPred ? 700 : 500, color: 'var(--color-text-primary,#333)' }}>
          {(p * 100).toFixed(1)}%
        </span>
      </div>
    </div>
  );
}

function HeatmapPair({ resultsBase, side, t }) {
  const base = process.env.PUBLIC_URL + '/' + resultsBase;
  return (
    <div style={{ flex: 1, minWidth: 220 }}>
      <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-text-secondary,#666)', marginBottom: 6 }}>
        {t(side === 'left' ? 'demo.leftEye' : 'demo.rightEye')}
      </div>
      <figure style={{ margin: 0 }}>
        {/* Analysis-frame overlay — mirror left eyes back to the original
            orientation (matches the live Grad-CAM block). */}
        <img
          src={`${base}/attention_overlay/${side}.png`}
          alt={`Attention overlay ${side}`}
          style={{
            width: '100%', display: 'block', borderRadius: 6, background: '#000',
            transform: side === 'left' ? 'scaleX(-1)' : undefined,
          }}
        />
        <figcaption style={{ fontSize: 10, marginTop: 4, color: 'var(--color-text-secondary,#666)' }}>
          {t('demo.viz.overlay')}
        </figcaption>
      </figure>
    </div>
  );
}

function VisualizationBlock({ caseRef, leftPresent, rightPresent, t }) {
  const explainable = caseRef && caseRef.explainable && caseRef.resultsBase;
  return (
    <div style={{ marginTop: 14 }}>
      <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-text-secondary,#666)', marginBottom: 6 }}>
        {t('demo.viz.title')}
      </div>
      {explainable ? (
        <>
          <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
            {rightPresent && <HeatmapPair resultsBase={caseRef.resultsBase} side="right" t={t} />}
            {leftPresent && <HeatmapPair resultsBase={caseRef.resultsBase} side="left" t={t} />}
          </div>
          <Note>{t('demo.viz.disclaimer')}</Note>
        </>
      ) : (
        <Note>{t('demo.viz.unavailable')}</Note>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main page
// ---------------------------------------------------------------------------
// Access-code screen (TASK-Demo §C.2). Shown only when the backend reports
// `requires_password` and no valid code is held yet. A 4-digit PIN — no
// accounts, no login flow — adequate for a ~15-person academic beta.
//
// PIN_LENGTH and the digits-only filter must match the shared secret in
// `demo/.demo-password` (a 4-digit numeric code). If that secret is ever
// changed to a different length or to non-numeric characters, this screen can
// no longer express it — change both together.
const PIN_LENGTH = 4;

function PasswordGate({ onUnlock, t }) {
  const [pin, setPin] = useState('');
  const [status, setStatus] = useState('idle'); // idle | checking | denied
  const [focused, setFocused] = useState(true);
  const inputRef = useRef(null);
  // Guards against re-submitting the same completed PIN (the auto-submit
  // effect re-runs whenever `status` settles back to idle).
  const submittedRef = useRef('');

  const submit = async (code) => {
    if (code.length !== PIN_LENGTH || submittedRef.current === code) return;
    submittedRef.current = code;
    setStatus('checking');
    try {
      const ok = await verifyPassword(code);
      if (ok) {
        setPassword(code);        // persist for subsequent protected requests
        onUnlock();
        return;
      }
    } catch {
      // Network error reaching the backend — treated as denied, same copy.
    }
    setStatus('denied');
    // Clear the cells so the next attempt starts from empty underscores; the
    // shake plays on the still-filled cells for one animation frame first.
    setTimeout(() => {
      setPin('');
      submittedRef.current = '';
      if (inputRef.current) inputRef.current.focus();
    }, 450);
  };

  // Focus trap. The gate is the only thing on the page, so the caret must never
  // end up anywhere else: a click on any blank area, or any other element
  // stealing focus, puts it straight back on the PIN field, and typing works
  // immediately after the tab regains window focus. `pointerdown` is cancelled
  // rather than corrected afterwards, so focus never visibly leaves.
  useEffect(() => {
    const isSelf = (el) => el && el === inputRef.current;
    const refocus = () => {
      const el = inputRef.current;
      if (el && !el.disabled && document.activeElement !== el) el.focus();
    };
    const onPointerDown = (e) => {
      if (isSelf(e.target)) return;
      e.preventDefault();
      refocus();
    };
    const onFocusIn = (e) => { if (!isSelf(e.target)) refocus(); };
    document.addEventListener('pointerdown', onPointerDown);
    document.addEventListener('focusin', onFocusIn);
    window.addEventListener('focus', refocus);
    return () => {
      document.removeEventListener('pointerdown', onPointerDown);
      document.removeEventListener('focusin', onFocusIn);
      window.removeEventListener('focus', refocus);
    };
  }, []);

  // The input is `disabled` while a code is being checked, which drops focus.
  // Take it back the moment the check settles, so a rejected code can be
  // retyped without clicking anything.
  useEffect(() => {
    if (status !== 'checking' && inputRef.current) inputRef.current.focus();
  }, [status]);

  // Fires the check the moment the last digit lands — no button to press.
  const onChange = (e) => {
    const next = e.target.value.replace(/\D/g, '').slice(0, PIN_LENGTH);
    setPin(next);
    if (status === 'denied' && next.length < PIN_LENGTH) setStatus('idle');
    if (next.length === PIN_LENGTH) submit(next);
  };

  const busy = status === 'checking';
  const denied = status === 'denied';
  const cells = Array.from({ length: PIN_LENGTH }, (_, i) => pin[i] || '');
  // Index of the cell the caret sits on (only while focused and not full).
  const activeIdx = focused && !busy ? Math.min(pin.length, PIN_LENGTH - 1) : -1;

  return (
    <div style={{ maxWidth: 420, margin: '48px auto', textAlign: 'center' }}>
      <h2 style={{ fontSize: 16, fontWeight: 700, color: 'var(--color-text-primary,#222)', marginBottom: 6 }}>
        {t('demo.gate.title')}
      </h2>
      <p style={{ fontSize: 12, color: 'var(--color-text-secondary,#666)', lineHeight: 1.55, marginBottom: 26 }}>
        {t('demo.gate.prompt')}
      </p>

      {/* The cells are pure presentation; a single transparent input laid over
          them owns the value, so paste, backspace, autofill of an SMS-style
          one-time code and the mobile numeric keypad all work unchanged. */}
      <div
        className={denied ? 'pin-row pin-shake' : 'pin-row'}
        onClick={() => inputRef.current && inputRef.current.focus()}
        style={{
          position: 'relative', display: 'flex', justifyContent: 'center',
          gap: 14, marginBottom: 18, cursor: 'text',
        }}
      >
        {cells.map((d, i) => (
          <div
            key={i}
            style={{
              width: 54, height: 74, display: 'flex', flexDirection: 'column',
              alignItems: 'center', justifyContent: 'flex-end', userSelect: 'none',
            }}
          >
            <div
              style={{
                fontSize: 40, lineHeight: 1, fontWeight: 600, fontVariantNumeric: 'tabular-nums',
                color: denied ? C.redT : 'var(--color-text-primary,#222)',
                marginBottom: 12, opacity: d ? 1 : 0,
                transform: d ? 'translateY(0) scale(1)' : 'translateY(6px) scale(0.9)',
                transition: 'opacity 120ms ease-out, transform 120ms ease-out',
              }}
            >
              {d || '0'}
            </div>
            <div
              className={i === activeIdx && !d ? 'pin-bar pin-bar-active' : 'pin-bar'}
              style={{
                width: '100%', height: 5, borderRadius: 3,
                background: denied ? C.red : (d || i === activeIdx) ? C.teal : 'var(--color-border-secondary,#ccc)',
                transition: 'background 150ms ease-out',
              }}
            />
          </div>
        ))}
        <input
          ref={inputRef}
          type="text"
          inputMode="numeric"
          pattern="[0-9]*"
          autoComplete="one-time-code"
          maxLength={PIN_LENGTH}
          value={pin}
          autoFocus
          disabled={busy}
          onChange={onChange}
          onFocus={() => setFocused(true)}
          onBlur={() => setFocused(false)}
          aria-label={t('demo.gate.placeholder')}
          style={{
            position: 'absolute', inset: 0, width: '100%', height: '100%',
            opacity: 0, border: 'none', background: 'transparent',
            font: 'inherit', color: 'transparent', caretColor: 'transparent',
            cursor: 'text', outline: 'none',
          }}
        />
      </div>

      {/* Fixed-height status line so the cells do not jump between states. */}
      <div style={{ minHeight: 32, fontSize: 11, lineHeight: 1.5 }}>
        {busy && <span style={{ color: 'var(--color-text-secondary,#666)' }}>{t('demo.gate.checking')}</span>}
        {denied && <span style={{ color: C.redT }}>{t('demo.gate.denied')}</span>}
        {!busy && !denied && <span style={{ color: 'var(--color-text-tertiary,#999)' }}>{t('demo.gate.hint')}</span>}
      </div>
    </div>
  );
}

export default function Demo() {
  const { t } = useLang();
  const [leftImg, setLeftImg] = useState(null);
  const [rightImg, setRightImg] = useState(null);
  const [running, setRunning] = useState(false);
  const [result, setResult] = useState(null);
  const [feedbackMode, setFeedbackMode] = useState(null); // 'confirm' | 'reject' | null
  const [correctedGrade, setCorrectedGrade] = useState(0);
  const [toast, setToast] = useState('');
  const [history, setHistory] = useState([]);
  // Tracks the active sample case (from WALKTHROUGH_POOL) so the result
  // panel can show pre-generated Grad-CAM + attention overlay. Any manual
  // upload or per-eye clear resets this to null — we cannot show heatmaps
  // for images that don't have a pre-generated companion under
  // `pipeline/dr0N/results/`.
  const [caseRef, setCaseRef] = useState(null);
  // Backend health. `health` is the /api/health payload (or null when the
  // backend is unreachable). `healthChecked` flips once the probe resolves.
  const [health, setHealth] = useState(null);
  const [healthChecked, setHealthChecked] = useState(false);
  // Collapsible "Additional info" block: the detailed per-image view (OD/fovea
  // centres & discs + step-by-step preprocessing stages). Collapsed by default.
  const [showDetail, setShowDetail] = useState(false);
  // Latches true the first time the block is opened. The heavy VisionWidget
  // (which fires a backend /visualize on mount) stays unmounted until then, so
  // simply loading an image does not trigger detector work; once opened it
  // stays mounted so re-collapsing/expanding animates without re-fetching.
  const [detailOpened, setDetailOpened] = useState(false);
  // Inside the detail block only one eye is shown at a time; a single chip in
  // the header toggles between them (like the Lite/Full and EN/ҚАЗ switches).
  // Defaults to the left eye (OS); the effect below falls back to whichever eye
  // is actually available when only one slot is filled.
  const [detailEye, setDetailEye] = useState('left');
  // Access gate (TASK-Demo §C.2/D). `authed` is true when the demo body is
  // unlocked: either the backend reports no password requirement / is offline
  // (the UI stays browsable; inference itself still needs a live backend), or
  // the user has supplied a valid password (revalidated from sessionStorage).
  const [authed, setAuthed] = useState(false);
  useEffect(() => {
    let alive = true;
    getHealth().then(async (h) => {
      if (!alive) return;
      setHealth(h);
      setHealthChecked(true);
      // No live gate to satisfy → unlock immediately (offline demo included).
      if (!h || !h.requires_password) { setAuthed(true); return; }
      // Gate active: try a previously stored password silently.
      const stored = getPassword();
      if (stored) {
        try { if (await verifyPassword(stored)) setAuthed(true); } catch { /* offline */ }
      }
    });
    return () => { alive = false; };
  }, []);
  // Real model is usable only when the backend is up AND a real checkpoint is
  // loaded (a boot without a checkpoint runs on random weights — meaningless).
  const apiReady = !!(health && health.checkpoint_loaded);
  // Preprocessing visualizations (/api/visualize, /api/gradcam) only need the
  // backend reachable — /api/visualize is checkpoint-free, so the "what the
  // model sees" widget lights up even before the model is trained.
  const liveVisuals = !!health;

  const eyes = useMemo(() => {
    const list = [];
    if (leftImg)  list.push({ eye: 'left',  src: leftImg.src,  name: leftImg.name  || 'left'  });
    if (rightImg) list.push({ eye: 'right', src: rightImg.src, name: rightImg.name || 'right' });
    return list;
  }, [leftImg, rightImg]);

  // Eyes that have a renderable detail widget: the slot has an image AND a
  // source of detail exists (ground-truth markers, or the live backend for the
  // detector path). Drives the per-eye switch in the "Additional info" block.
  const detailEyes = useMemo(() => {
    // Right eye (OD) first so its switch button sits on the left.
    const list = [];
    if (rightImg && (rightImg.gt || liveVisuals)) list.push('right');
    if (leftImg  && (leftImg.gt  || liveVisuals)) list.push('left');
    return list;
  }, [leftImg, rightImg, liveVisuals]);

  // Keep the selected detail eye valid: if it disappears (slot cleared / no
  // detail source) fall back to the first available eye, preferring right (OD).
  useEffect(() => {
    if (detailEyes.length && !detailEyes.includes(detailEye)) {
      setDetailEye(detailEyes[0]);
    }
  }, [detailEyes, detailEye]);

  // Swap the two slots — used by the wrong-slot warning chip. Both images
  // (with their attached `checks`) move to the opposite slot; the laterality
  // check then re-evaluates against the new slot and the warning clears.
  const swapSlots = () => {
    setLeftImg(rightImg);
    setRightImg(leftImg);
    setResult(null);
    setFeedbackMode(null);
  };

  const reset = (keepHistory = true) => {
    setLeftImg(null);
    setRightImg(null);
    setCaseRef(null);
    setResult(null);
    setFeedbackMode(null);
    setCorrectedGrade(0);
    if (!keepHistory) setHistory([]);
  };

  const handleRun = async () => {
    if (eyes.length === 0) return;
    // No simulator fallback — inference requires a live backend with a loaded
    // checkpoint. If it is not ready, surface an error and stop.
    if (!apiReady) {
      setToast(t('demo.modelStatus.unavailable'));
      setTimeout(() => setToast(''), 5000);
      return;
    }
    setRunning(true);
    setResult(null);
    setFeedbackMode(null);
    try {
      const r = await predictPatient(eyes);
      setResult(normalizeApiResult(r, eyes));
    } catch (e) {
      console.error(e);
      setToast(t('demo.modelStatus.error'));
      setTimeout(() => setToast(''), 5000);
    } finally {
      setRunning(false);
    }
  };

  // Pick handler for an eye slot. On a manual upload we also try to match the
  // file against IDRiD localization ground truth by filename (IDRiD_NNN); if it
  // matches, we attach the `gt` payload so the preprocessing/centre overlay
  // renders for it (the overlay only shows for GT-backed images).
  const handlePick = (setImg) => (img) => {
    setImg(img);
    if (img && img.fromUpload) {
      setCaseRef(null);
      matchIdridUpload(img.name, img.src).then((gt) => {
        if (gt) setImg((cur) => (cur && cur.src === img.src ? { ...cur, gt } : cur));
      });
    }
  };

  // Roll a random IDRiD patient (one left + one right eye, same DR grade), each
  // carrying ground-truth OD + fovea centres. The left-anatomy image goes to the
  // LEFT slot and the right-anatomy image to the RIGHT slot, so both eyes show
  // GT markers VisionWidget overlays directly. If the IDRiD manifest is empty
  // (prep script not yet run), fall back to a walkthrough bilateral case.
  const loadRandomSample = () => {
    const patient = pickRandomIdridPatient();
    if (patient) {
      // Insert the random patient's images as PLAIN images — no ground-truth
      // payload. They are then detected, correctable, and classified exactly
      // like an uploaded snapshot (the detector finds OD/fovea, the clinician
      // can drag-correct, and DR is graded the same way). We deliberately drop
      // the IDRiD helper data (centres, FOV mask) so nothing is pre-supplied.
      setLeftImg({ src: process.env.PUBLIC_URL + '/' + patient.left.image, name: patient.left.id, fromUpload: false });
      setRightImg({ src: process.env.PUBLIC_URL + '/' + patient.right.image, name: patient.right.id, fromUpload: false });
      setCaseRef(null); // IDRiD samples have no pre-rendered explainability assets
    } else {
      const w = pickRandomWalkthrough(WALKTHROUGH_POOL);
      if (!w) return;
      setLeftImg({  src: process.env.PUBLIC_URL + '/' + w.left,  name: w.left,  fromUpload: false });
      setRightImg({ src: process.env.PUBLIC_URL + '/' + w.right, name: w.right, fromUpload: false });
      setCaseRef(w);
    }
    setResult(null);
    setFeedbackMode(null);
  };

  const submitFeedback = (verdict) => {
    if (!result) return;
    const entry = {
      id: Date.now(),
      timestamp: new Date().toISOString(),
      images: eyes.map(e => ({ eye: e.eye, source: e.name })),
      predicted: result.pred,
      confidence: Number(result.confidence.toFixed(4)),
      probs: result.probs.map(p => Number(p.toFixed(4))),
      verdict,
      corrected_grade: verdict === 'confirmed' ? result.pred : correctedGrade,
      latency_ms: result.latencyMs,
      model: 'config-D (pipeline + EfficientNet-B3)',
    };
    setHistory(h => [entry, ...h]);
    setToast(t('demo.thanks'));
    setTimeout(() => setToast(''), 2500);
    setFeedbackMode(null);
  };

  const exportJsonl = () => {
    if (history.length === 0) return;
    const jsonl = history.map(h => JSON.stringify(h)).join('\n');
    const blob = new Blob([jsonl], { type: 'application/x-ndjson' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `dr-relabel-${new Date().toISOString().replace(/[:.]/g, '-')}.jsonl`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Block the demo body behind the access screen only when the backend
  // actively requires a password and we are not yet authenticated. A null/
  // offline health never gates — the UI stays browsable without a backend.
  if (healthChecked && health && health.requires_password && !authed) {
    return <PasswordGate onUnlock={() => setAuthed(true)} t={t} />;
  }

  return (
    <div>
      {/* Header */}
      <div style={{ marginBottom: 20 }}>
        <h2 style={{ fontSize: 18, fontWeight: 700, color: 'var(--color-text-primary,#222)', margin: '0 0 4px 0' }}>
          {t('demo.title')}
        </h2>
        <p style={{ fontSize: 12, color: 'var(--color-text-secondary,#666)', margin: '0 0 8px 0', lineHeight: 1.55 }}>
          {t('demo.subtitle')}
        </p>
        {/* Framing block (TASK-Demo D.1) — muted, no marketing copy. Laid out
            as a row: the two text lines form a column on the left, the random
            sample button sits on the right and stretches to the full block
            height (both lines), not just the first line. */}
        <div style={{
          fontSize: 11, color: 'var(--color-text-secondary,#777)', lineHeight: 1.6,
          borderLeft: `2px solid ${C.teal}`, paddingLeft: 10, margin: '0 0 8px 0',
          display: 'flex', alignItems: 'stretch', justifyContent: 'space-between',
          gap: 10, flexWrap: 'nowrap',
        }}>
          {/* Text keeps priority and stays on its line; when the row gets tight
              the button yields width first (its label re-flows within the height
              it already stretches to) instead of the text wrapping. */}
          <div style={{ flex: '1 1 auto', minWidth: 0 }}>
            <div style={{ fontWeight: 700 }}>{t('demo.framing.line1')}</div>
            <div>{t('demo.framing.line2')}</div>
          </div>
          <button
            onClick={loadRandomSample}
            title={t('demo.randomHint')}
            style={{
              display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
              gap: 6, flexGrow: 0, flexShrink: 100, minWidth: 0, alignSelf: 'stretch',
              padding: '6px 13px', fontSize: 10.5, fontWeight: 600,
              letterSpacing: '0.02em', fontVariant: 'small-caps',
              background: 'transparent', color: C.tealT,
              border: `1px solid ${C.teal}`, borderRadius: 5, cursor: 'pointer',
              transition: 'background 0.15s ease, box-shadow 0.15s ease',
            }}
            onMouseEnter={(e) => { e.currentTarget.style.background = C.tealBg; }}
            onMouseLeave={(e) => { e.currentTarget.style.background = 'transparent'; }}
          >
            {/* Shuffle glyph — a quiet "draw a sample" cue in place of the dice emoji. */}
            <svg
              width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor"
              strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"
              style={{ flexShrink: 0 }}
            >
              <path d="M16 3h5v5" />
              <path d="M4 20 21 3" />
              <path d="M21 16v5h-5" />
              <path d="m15 15 6 6" />
              <path d="m4 4 5 5" />
            </svg>
            {t('demo.random')}
          </button>
        </div>
        {/* <div style={{ fontSize: 10, color: C.amberT, background: C.amberBg, padding: '6px 10px', borderRadius: 6, display: 'inline-block' }}>
          ⚠ {t('demo.disclaimer')}
        </div> */}
      </div>

      {/* Upload section */}
      <Sec title={t('demo.uploadSection')}>
        {/* Right eye (OD) shown on the LEFT, left eye (OS) on the RIGHT — matches
            the clinical convention for displaying fundus pairs. */}
        <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
          <EyeSlot
            label={t('demo.rightEye')}
            eye="right"
            image={rightImg}
            onPick={handlePick(setRightImg)}
            onClear={() => { setRightImg(null); setCaseRef(null); setResult(null); setFeedbackMode(null); }}
            onSwap={swapSlots}
            t={t}
          />
          <EyeSlot
            label={t('demo.leftEye')}
            eye="left"
            image={leftImg}
            onPick={handlePick(setLeftImg)}
            onClear={() => { setLeftImg(null); setCaseRef(null); setResult(null); setFeedbackMode(null); }}
            onSwap={swapSlots}
            t={t}
          />
        </div>

        {/* Additional info: a collapsible block revealing the detailed per-image
            view — OD/fovea centres & discs the detector found, plus the result
            of each preprocessing stage as its own slide (TASK-Demo D.2). Shown
            once at least one slot has an image and a source of detail exists
            (ground-truth markers, or the live backend for the detector path). */}
        {(leftImg || rightImg) && (liveVisuals || leftImg?.gt || rightImg?.gt) && (() => {
          // One eye at a time, picked by the switch below (defaults to right).
          // The chosen slot is rendered with GT markers when it has them,
          // otherwise via the live detector path. Computed unconditionally so
          // the panel's contents stay mounted across the open/close animation.
          const selected = detailEyes.includes(detailEye) ? detailEye : detailEyes[0];
          const img = selected === 'left' ? leftImg : rightImg;
          const toggle = () => setShowDetail((v) => { if (!v) setDetailOpened(true); return !v; });
          return (
            <div style={{ marginTop: 12 }}>
              {/* Accordion header row. Doubles as the top of the panel when
                  open: the bottom corners square off to fuse with the body
                  below. The clickable title (left) toggles the panel; the eye
                  switch (right) is a sibling button — not nested — so clicking
                  it never toggles the panel. */}
              <div style={{
                display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap',
                padding: '6px 12px',
                background: C.tealBg,
                border: `1px solid ${C.teal}`,
                borderRadius: showDetail ? '6px 6px 0 0' : 6,
                transition: 'border-radius 0.25s ease',
              }}>
                <button
                  type="button"
                  onClick={toggle}
                  aria-expanded={showDetail}
                  style={{
                    display: 'flex', alignItems: 'center', gap: 8,
                    flex: 1, minWidth: 0, padding: '2px 0',
                    fontSize: 12, fontWeight: 600, textAlign: 'left',
                    background: 'transparent', color: C.tealT,
                    border: 'none', cursor: 'pointer',
                  }}
                >
                  <span style={{
                    fontSize: 11, display: 'inline-block', lineHeight: 1, flexShrink: 0,
                    transform: showDetail ? 'rotate(90deg)' : 'rotate(0deg)',
                    transition: 'transform 0.25s ease',
                  }}>▸</span>
                  {t('demo.vision.additionalInfo')}
                </button>

                {/* Single eye switch (merged from the old two buttons). Shows
                    the active eye and flips to the other on click — same chip
                    pattern as Lite/Full and EN/ҚАЗ. Disabled (label only) when
                    just one eye is loaded, since there is nothing to switch to. */}
                {detailEyes.length > 0 && (() => {
                  const dual = detailEyes.length > 1;
                  return (
                    <button
                      type="button"
                      className="chip-toggle"
                      disabled={!dual}
                      onClick={() => setDetailEye(selected === 'left' ? 'right' : 'left')}
                      title={dual
                        ? `${selected === 'left' ? t('demo.leftEye') : t('demo.rightEye')} — ${t('demo.vision.additionalInfo')}`
                        : (selected === 'left' ? t('demo.leftEye') : t('demo.rightEye'))}
                      style={{ flexShrink: 0, cursor: dual ? 'pointer' : 'default', opacity: dual ? 1 : 0.7 }}
                    >
                      <span aria-hidden="true">👁</span>
                      <span>{selected === 'left' ? t('demo.leftEye') : t('demo.rightEye')}</span>
                    </button>
                  );
                })()}
              </div>

              {/* Smoothly expanding body: the grid-template-rows 0fr→1fr trick
                  animates height without measuring. Holds the full VisionWidget
                  for the eye selected in the header — analysis-space input,
                  OD·fovea markers, FOV-mask toggle, the step-by-step
                  preprocessing-stage slides. */}
              <div
                aria-hidden={!showDetail}
                style={{
                  display: 'grid',
                  gridTemplateRows: showDetail ? '1fr' : '0fr',
                  transition: 'grid-template-rows 0.3s ease',
                  border: `1px solid ${showDetail ? C.teal : 'transparent'}`,
                  borderTop: 'none', borderRadius: '0 0 6px 6px',
                }}
              >
                <div style={{ overflow: 'hidden', minHeight: 0 }}>
                  <div style={{
                    padding: 10,
                    pointerEvents: showDetail ? 'auto' : 'none',
                  }}>
                    {/* Selected eye's detailed view — GT-backed (markers + mask
                        render even offline) or the live detector path (learned
                        OD/fovea overlay, drag-correctable centres, stage slides).
                        Mounted only after the panel has been opened once, then
                        kept alive so toggling stays smooth and refetch-free. */}
                    {img && detailOpened && (
                      <VisionWidget
                        key={selected}
                        src={img.src}
                        eye={selected}
                        name={img.name}
                        enabled={liveVisuals}
                        gt={img.gt}
                        t={t}
                      />
                    )}
                  </div>
                </div>
              </div>
            </div>
          );
        })()}

      </Sec>

      {/* Run section */}
      <Sec title={t('demo.runSection')}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' }}>
          <button
            onClick={handleRun}
            disabled={running || eyes.length === 0}
            style={{
              padding: '8px 18px', fontSize: 12, fontWeight: 600,
              background: (running || eyes.length === 0) ? C.gray : C.teal,
              color: 'white', border: 'none', borderRadius: 6,
              cursor: (running || eyes.length === 0) ? 'not-allowed' : 'pointer',
            }}
          >
            {running ? t('demo.running') : t('demo.runButton')}
          </button>
          {eyes.length === 0 && (
            <span style={{ fontSize: 11, color: C.red }}>{t('demo.needAtLeastOne')}</span>
          )}
          {eyes.length > 0 && !running && (
            <span style={{ fontSize: 11, color: 'var(--color-text-secondary,#666)' }}>
              {eyes.length} {eyes.length === 1 ? 'image' : 'images'}
            </span>
          )}
        </div>
      </Sec>

      {/* Result section */}
      {result && (
        <Sec title={t('demo.resultSection')}>
          <div style={{
            display: 'flex', gap: 12, flexWrap: 'wrap',
            padding: 14, borderRadius: 10,
            background: result.pred >= 2 ? C.coralBg : C.tealBg,
            border: `1px solid ${result.pred >= 2 ? C.coral : C.teal}`,
          }}>
            <div style={{ flex: 1, minWidth: 180 }}>
              <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.06em', textTransform: 'uppercase', color: result.pred >= 2 ? C.coralT : C.tealT, opacity: 0.8 }}>
                {t('demo.predictedGrade')}
              </div>
              <div style={{ fontSize: 22, fontWeight: 700, color: result.pred >= 2 ? C.coralT : C.tealT, marginTop: 2 }}>
                {t('demo.grade.' + result.pred)}
              </div>
              <div style={{ fontSize: 11, color: 'var(--color-text-secondary,#555)', marginTop: 6 }}>
                {t('demo.confidence')}: <strong>{(result.confidence * 100).toFixed(1)}%</strong>
                {' · '}
                {t('demo.referable')}: <strong>{result.pred >= 2 ? t('demo.yes') : t('demo.no')}</strong>
                {' · '}
                {t('demo.latency')}: <strong>{result.latencyMs} ms</strong>
              </div>
            </div>
            <div style={{ flex: 1, minWidth: 220 }}>
              <div style={{ fontSize: 10, fontWeight: 600, color: 'var(--color-text-secondary,#666)', marginBottom: 4 }}>
                {t('demo.classProbs')}
              </div>
              {result.probs.map((p, i) => (
                <ProbabilityBar key={i} idx={i} p={p} isPred={i === result.pred} t={t} />
              ))}
            </div>
          </div>

          {/* Per-eye breakdown */}
          {result.perEye.length > 1 && (
            <div style={{ marginTop: 12 }}>
              <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-text-secondary,#666)', marginBottom: 6 }}>
                {t('demo.perEye')}
              </div>
              <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
                {result.perEye.map((eye, i) => (
                  <div key={i} style={{
                    flex: 1, minWidth: 200, padding: '8px 12px',
                    background: 'var(--color-background-secondary,#f7f7f5)', borderRadius: 8,
                    borderLeft: `3px solid ${eye.result.pred >= 2 ? C.coral : C.teal}`,
                  }}>
                    <div style={{ fontSize: 10, color: 'var(--color-text-secondary,#666)', fontWeight: 600 }}>
                      {t(eye.eye === 'left' ? 'demo.leftEye' : 'demo.rightEye')}
                    </div>
                    <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--color-text-primary,#222)' }}>
                      {t('demo.grade.' + eye.result.pred)}
                    </div>
                    <div style={{ fontSize: 10, color: 'var(--color-text-secondary,#666)', marginTop: 2 }}>
                      {(eye.result.confidence * 100).toFixed(1)}% · {eye.result.latencyMs} ms
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Grad-CAM heatmap + attention overlay.
              Live (from the checkpoint) for custom uploads when the real model
              is active; pre-rendered walkthrough assets otherwise. */}
          {apiReady && caseRef === null && eyes.length > 0 ? (
            <LiveVisualizationBlock eyes={eyes} t={t} />
          ) : (
            <VisualizationBlock
              caseRef={caseRef}
              leftPresent={!!leftImg}
              rightPresent={!!rightImg}
              t={t}
            />
          )}
        </Sec>
      )}

      {/* Feedback section */}
      {result && (
        <Sec title={t('demo.feedbackSection')} note={t('demo.feedbackHint')}>
          <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', alignItems: 'center' }}>
            <button
              onClick={() => { setFeedbackMode('confirm'); submitFeedback('confirmed'); }}
              style={{
                padding: '8px 16px', fontSize: 12, fontWeight: 600,
                background: C.green, color: 'white', border: 'none',
                borderRadius: 6, cursor: 'pointer',
              }}
            >
              ✓ {t('demo.confirm')}
            </button>
            <button
              onClick={() => setFeedbackMode('reject')}
              style={{
                padding: '8px 16px', fontSize: 12, fontWeight: 600,
                background: 'white', color: C.red,
                border: `1px solid ${C.red}`, borderRadius: 6, cursor: 'pointer',
              }}
            >
              ✕ {t('demo.reject')}
            </button>
          </div>
          {feedbackMode === 'reject' && (
            <div style={{
              marginTop: 12, padding: 12, borderRadius: 8,
              background: C.redBg, border: `1px solid ${C.red}`,
              display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap',
            }}>
              <label style={{ fontSize: 11, fontWeight: 600, color: C.redT }}>
                {t('demo.correctGrade')}:
              </label>
              <select
                value={correctedGrade}
                onChange={(e) => setCorrectedGrade(parseInt(e.target.value, 10))}
                style={{ padding: '4px 8px', fontSize: 11, border: '1px solid var(--color-border-secondary,#ccc)', borderRadius: 4 }}
              >
                {[0, 1, 2, 3, 4].map(g => (
                  <option key={g} value={g}>{t('demo.grade.' + g)}</option>
                ))}
              </select>
              <button
                onClick={() => submitFeedback('rejected')}
                style={{
                  padding: '6px 14px', fontSize: 11, fontWeight: 600,
                  background: C.red, color: 'white', border: 'none',
                  borderRadius: 4, cursor: 'pointer',
                }}
              >
                {t('demo.submit')}
              </button>
            </div>
          )}
          {toast && (
            <div style={{
              marginTop: 10, padding: '8px 12px', borderRadius: 6,
              background: C.greenBg, color: C.greenT, fontSize: 11, fontWeight: 600,
            }}>
              ✓ {toast}
            </div>
          )}
        </Sec>
      )}

      {/* History / relabeling buffer */}
      <Sec title={`${t('demo.historyTitle')} (${history.length})`}>
        <div style={{ display: 'flex', gap: 8, marginBottom: 10 }}>
          <button
            onClick={exportJsonl}
            disabled={history.length === 0}
            style={{
              padding: '6px 12px', fontSize: 11, fontWeight: 600,
              background: history.length === 0 ? C.gray : C.blue,
              color: 'white', border: 'none', borderRadius: 4,
              cursor: history.length === 0 ? 'not-allowed' : 'pointer',
            }}
          >
            ⬇ {t('demo.export')}
          </button>
          <button
            onClick={() => setHistory([])}
            disabled={history.length === 0}
            style={{
              padding: '6px 12px', fontSize: 11,
              background: 'white', color: history.length === 0 ? C.gray : C.red,
              border: `1px solid ${history.length === 0 ? C.gray : C.red}`,
              borderRadius: 4, cursor: history.length === 0 ? 'not-allowed' : 'pointer',
            }}
          >
            {t('demo.clearAll')}
          </button>
        </div>
        {history.length === 0 ? (
          <Note>{t('demo.historyEmpty')}</Note>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11 }}>
              <thead>
                <tr style={{ borderBottom: '2px solid var(--color-border-secondary,#ccc)' }}>
                  <th style={{ padding: '5px 8px', textAlign: 'left', fontWeight: 600 }}>{t('demo.col.time')}</th>
                  <th style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>{t('demo.col.images')}</th>
                  <th style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>{t('demo.col.predicted')}</th>
                  <th style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>{t('demo.col.verdict')}</th>
                  <th style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>{t('demo.col.corrected')}</th>
                </tr>
              </thead>
              <tbody>
                {history.map(h => (
                  <tr key={h.id} style={{ borderBottom: '1px solid var(--color-border-tertiary,#eee)' }}>
                    <td style={{ padding: '5px 8px', fontFamily: 'monospace', fontSize: 10, color: 'var(--color-text-secondary,#666)' }}>
                      {new Date(h.timestamp).toLocaleTimeString()}
                    </td>
                    <td style={{ padding: '5px 8px', textAlign: 'center' }}>{h.images.length}</td>
                    <td style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>
                      {t('demo.gradeShort.' + h.predicted)} ({(h.confidence * 100).toFixed(0)}%)
                    </td>
                    <td style={{ padding: '5px 8px', textAlign: 'center' }}>
                      <span style={{
                        padding: '2px 6px', borderRadius: 3, fontSize: 10, fontWeight: 600,
                        background: h.verdict === 'confirmed' ? C.greenBg : C.redBg,
                        color: h.verdict === 'confirmed' ? C.greenT : C.redT,
                      }}>
                        {t('demo.verdict.' + h.verdict)}
                      </span>
                    </td>
                    <td style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>
                      {t('demo.gradeShort.' + h.corrected_grade)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Sec>

      {/* Provenance string (TASK-Demo D.7) — what the committee can quote. */}
      {health && (
        <div style={{ fontSize: 9, color: C.gray, marginTop: 4, fontFamily: 'monospace' }}>
          version {health.version} · git {health.git_sha || 'n/a'} · checkpoint {health.checkpoint}
          {health.checkpoint_loaded ? '' : ' (not loaded)'} · {health.device}
        </div>
      )}

      <div style={{ marginTop: 14 }}>
        <button onClick={() => reset(true)} style={{
          fontSize: 10, padding: '4px 10px', background: 'transparent',
          color: 'var(--color-text-secondary,#666)',
          border: '1px solid var(--color-border-secondary,#ccc)',
          borderRadius: 4, cursor: 'pointer',
        }}>
          ↺ Reset case
        </button>
      </div>
    </div>
  );
}
