// record_demo.js — drive the published demo through the storyboard and record it.
//
//   node record_demo.js                 # full run, writes recording/ + beat_times.json
//   node record_demo.js --to B08        # rehearsal: stop after beat B08
//   node record_demo.js --speed 4       # rehearsal at 4x (timings are NOT usable for captions)
//
// The beats and their planned start times come from `beats.json` (generated by
// build_video.py from the storyboard). Every beat records the second it actually started
// into `beat_times.json`; feeding that back through
//     python build_video.py --anchors beat_times.json
// re-times the subtitles onto the real recording, so drift cannot desynchronise them.
//
// Two deliberate choices:
//   * the access PIN is seeded into sessionStorage before the app boots, so the gate never
//     appears and the code is never filmed;
//   * a synthetic cursor is drawn by an injected script, because Playwright's recorder does
//     not capture the real pointer — without it every click would look like magic.

const fs = require('fs');
const path = require('path');
const { chromium } = require('D:/mailbot/node_modules/playwright-core');

const HERE = __dirname;
const URL = 'https://dr-classification.pages.dev/';
const PIN = fs.readFileSync('D:/dissertation-project/demo/.demo-password', 'utf8').trim();
const IMG = path.join(HERE, 'patient_294');
const OUT = path.join(HERE, 'recording');
const ZOOM = 1.4;

const args = process.argv.slice(2);
const argOf = (name, fallback) => {
  const i = args.indexOf(name);
  return i >= 0 && args[i + 1] ? args[i + 1] : fallback;
};
const STOP_AFTER = argOf('--to', null);
const SPEED = Number(argOf('--speed', 1));

// ── injected page helpers ───────────────────────────────────────────────────
const CURSOR_SCRIPT = () => {
  const install = () => {
    if (document.getElementById('__cursor')) return;
    const dot = document.createElement('div');
    dot.id = '__cursor';
    dot.style.cssText = [
      'position:fixed', 'left:0', 'top:0', 'width:22px', 'height:22px',
      'margin:-11px 0 0 -11px', 'border-radius:50%',
      'background:rgba(29,158,117,0.35)', 'border:2px solid rgba(20,90,70,0.9)',
      'box-shadow:0 0 6px rgba(0,0,0,0.35)', 'pointer-events:none', 'z-index:2147483647',
      'transition:transform 90ms ease-out',
    ].join(';');
    document.body.appendChild(dot);
    const move = (e) => {
      dot.style.transform = `translate(${e.clientX}px, ${e.clientY}px)`;
    };
    document.addEventListener('mousemove', move, true);
    document.addEventListener('mousedown', () => { dot.style.width = '14px'; dot.style.height = '14px'; }, true);
    document.addEventListener('mouseup', () => { dot.style.width = '22px'; dot.style.height = '22px'; }, true);
  };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', install);
  else install();
};

// ── timing ──────────────────────────────────────────────────────────────────
let t0 = 0;
const now = () => (Date.now() - t0) / 1000;
const sleep = (s) => new Promise((r) => setTimeout(r, Math.max(0, (s * 1000) / SPEED)));
async function waitUntil(sec) {
  const target = sec / SPEED;
  const gap = target - now();
  if (gap > 0) await new Promise((r) => setTimeout(r, gap * 1000));
}

// ── interaction helpers (all pointer-driven, so the cursor is visible) ───────
async function moveTo(page, locator, { steps = 14 } = {}) {
  // The pointer API does not scroll for us the way locator.click() does, so an element
  // below the fold would be "clicked" outside the viewport and nothing would happen.
  await locator.scrollIntoViewIfNeeded({ timeout: 5000 }).catch(() => {});
  const box = await locator.boundingBox();
  if (!box) throw new Error('element has no box');
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2, { steps });
  return box;
}

async function click(page, locator) {
  await moveTo(page, locator);
  await sleep(0.18);
  await page.mouse.down();
  await sleep(0.09);
  await page.mouse.up();
}

function byText(page, text, { scope = 'button', last = false } = {}) {
  const loc = page.locator(scope, { hasText: text });
  return last ? loc.last() : loc.first();
}

async function scrollToText(page, text, block = 'center') {
  await page.evaluate(([needle, blk]) => {
    const walk = document.evaluate(
      `//*[not(self::script)][contains(normalize-space(text()), ${JSON.stringify(needle)})]`,
      document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
    (walk || document.body).scrollIntoView({ behavior: 'smooth', block: blk });
  }, [text, block]);
}

async function scrollBy(page, dy, chunks = 12) {
  for (let i = 0; i < chunks; i++) {
    await page.mouse.wheel(0, dy / chunks);
    await sleep(0.05);
  }
}

const nextSlide = (page) => byText(page, '→');
const prevSlide = (page) => byText(page, '←');

async function stepForward(page, times = 1, dwell = 0.9) {
  for (let i = 0; i < times; i++) { await click(page, nextSlide(page)); await sleep(dwell); }
}
async function stepBack(page, times = 1, dwell = 0.9) {
  for (let i = 0; i < times; i++) { await click(page, prevSlide(page)); await sleep(dwell); }
}

async function slideLabel(page) {
  return page.evaluate(() => {
    const t = document.body.innerText;
    const i = t.indexOf('Preprocessing stages');
    return t.slice(i, i + 120).split('\n').filter(Boolean).slice(0, 5).join(' | ');
  });
}

async function navTo(page, label) {
  await click(page, page.locator('nav button', { hasText: label }).first());
}

// ── the beats ───────────────────────────────────────────────────────────────
// Each entry is the action performed at the START of that beat; the rest of the beat is
// dwell time the captions play over.
const ACTIONS = {
  B01: async (page) => { await page.mouse.move(960, 300, { steps: 10 }); },

  B02: async (page) => { await moveTo(page, byText(page, 'Lite')); },

  B03: async (page) => {
    const inputs = page.locator('input[type="file"]');
    await moveTo(page, page.locator('text=Right eye (Oculus Dexter)').first());
    await inputs.nth(0).setInputFiles(path.join(IMG, '294_right.jpeg'));
    await sleep(2.2);
    await moveTo(page, page.locator('text=Left eye (Oculus Sinister)').first());
    await inputs.nth(1).setInputFiles(path.join(IMG, '294_left.jpeg'));
  },

  B04: async (page) => { await sleep(0.2); },

  B05: async (page) => {
    await click(page, byText(page, 'Additional info'));
    await sleep(2.0);
    const chip = page.locator('button', { hasText: /eye \(Oculus/ }).last();
    if (/Right eye/.test(await chip.innerText())) { await click(page, chip); await sleep(2.5); }
    console.log('   eye now:', (await chip.innerText()).replace(/\s+/g, ' ').trim());
    await scrollToText(page, 'Preprocessing stages', 'start');
    await sleep(1.0);
    await scrollBy(page, -90, 6);
  },

  B06: async (page) => { console.log('   slide:', await slideLabel(page)); },

  B07: async (page) => {                      // canonical flip, shown twice
    await stepForward(page, 1);
    await sleep(1.6);
    await stepBack(page, 1);
    await sleep(1.2);
    await stepForward(page, 1);
  },

  B08: async (page) => {                      // OD / fovea detection
    await stepForward(page, 1);
    await sleep(2.5);
    const heat = byText(page, 'probability heatmap');
    if (await heat.count()) {
      await click(page, heat);
      await sleep(3.0);
      await click(page, byText(page, 'probability heatmap'));
    }
  },

  B09: async (page) => { await stepForward(page, 1); },
  B10: async (page) => { await stepForward(page, 1); },
  B11: async (page) => { await stepForward(page, 1); },

  B12: async (page) => {                      // flat-field, A/B against the crop stage
    await stepForward(page, 1);
    await sleep(2.2);
    await stepBack(page, 2, 0.7);
    await sleep(1.4);
    await stepForward(page, 2, 0.7);
  },

  B13: async (page) => {                      // CLAHE, A/B against flat-field
    await stepForward(page, 1);
    await sleep(2.2);
    await stepBack(page, 1);
    await sleep(1.3);
    await stepForward(page, 1);
  },

  B14: async (page) => { await scrollToText(page, 'Channels at this stage', 'center'); },

  B15: async (page) => { await sleep(0.2); },

  B16: async (page) => {
    await scrollToText(page, '2. Run model', 'center');
    await sleep(1.2);
    await click(page, byText(page, 'Run inference'));
    await sleep(4.0);
    await scrollToText(page, '3. Model result', 'start');
  },

  B17: async (page) => { await scrollToText(page, 'Per-eye prediction', 'center'); },

  B18: async (page) => {
    await scrollToText(page, 'Visualization', 'start');
    await sleep(2.0);
    await scrollBy(page, 220, 10);
  },

  B19: async (page) => { await scrollToText(page, 'Interpretability evidence only', 'center'); },

  B20: async (page) => {
    await scrollToText(page, '4. Confirm or reject', 'center');
    await sleep(1.2);
    await click(page, byText(page, 'Confirm prediction'));
  },

  B21: async (page) => {
    await click(page, byText(page, 'Undo verdict'));
    await sleep(2.0);
    await click(page, byText(page, 'Reject'));
    await sleep(1.6);
    await page.selectOption('select', { index: 3 });   // DR3, one grade below the prediction
    await sleep(1.8);
    await click(page, byText(page, 'Add to training buffer'));
  },

  B22: async (page) => {
    await scrollToText(page, 'Relabeling buffer', 'start');
    await sleep(2.5);
    await scrollToText(page, 'Study totals', 'center');
    await sleep(2.0);
    await moveTo(page, byText(page, 'Export JSONL'));
  },

  B23: async (page) => {
    await scrollToText(page, 'Live Inference Demo', 'start');
    await sleep(1.0);
    await click(page, byText(page, 'Lite'));
    await sleep(2.0);
  },

  B24: async (page) => { await navTo(page, 'Overview'); await sleep(2.5); await scrollBy(page, 500, 14); },
  B25: async (page) => { await navTo(page, 'Pipeline'); await sleep(2.5); await scrollBy(page, 700, 16); },
  B26: async (page) => {
    await navTo(page, 'Architecture');
    await sleep(3.5);
    await scrollBy(page, 400, 10);
    await sleep(2.0);
    await navTo(page, 'Explainability');
  },
  B27: async (page) => { await navTo(page, 'Datasets'); await sleep(2.5); await scrollBy(page, 400, 10); },
  B28: async (page) => { await navTo(page, 'Exp 1 (H-1)'); await sleep(3.0); await scrollBy(page, 450, 12); },
  B29: async (page) => { await navTo(page, 'Exp 2 (H-2)'); await sleep(3.0); await scrollBy(page, 500, 12); },
  B30: async (page) => { await navTo(page, 'Exp 4 (H-5)'); await sleep(3.0); await scrollBy(page, 400, 10); },
  B31: async (page) => {
    await navTo(page, 'Exp 3 (H-4)');
    await sleep(4.0);
    await navTo(page, 'Exp 5 (H-4/H-7)');
    await sleep(2.0);
    await scrollBy(page, 300, 8);
  },
  B32: async (page) => {
    await navTo(page, 'Exp 6 (H-6)');
    await sleep(4.0);
    await navTo(page, 'Exp 7: Small Data');
  },
  B33: async (page) => {
    await navTo(page, 'Main Metrics');
    await sleep(3.5);
    await navTo(page, 'Statistical Tests');
  },
  B34: async (page) => { await navTo(page, 'Computational'); await sleep(2.5); await scrollBy(page, 350, 10); },
  B35: async (page) => {
    await navTo(page, 'Overview');
    await sleep(3.0);
    await click(page, byText(page, 'Full'));
  },
};

(async () => {
  const beats = JSON.parse(fs.readFileSync(path.join(HERE, 'beats.json'), 'utf8'));
  fs.mkdirSync(OUT, { recursive: true });

  const browser = await chromium.launch({ channel: 'chrome', headless: false });
  const ctx = await browser.newContext({
    viewport: { width: 1920, height: 1080 },
    recordVideo: { dir: OUT, size: { width: 1920, height: 1080 } },
  });
  await ctx.addInitScript((pin) => {
    try { sessionStorage.setItem('demo_password', pin); } catch (e) { /* ignore */ }
    try { localStorage.setItem('viewMode', 'lite'); } catch (e) { /* ignore */ }
  }, PIN);
  await ctx.addInitScript(CURSOR_SCRIPT);

  const page = await ctx.newPage();
  const videoStartedAt = Date.now();          // the recorder starts with the page
  await page.goto(URL, { waitUntil: 'domcontentloaded', timeout: 90000 });
  await page.waitForTimeout(6000);
  await page.evaluate((z) => { document.documentElement.style.zoom = String(z); }, ZOOM);
  await page.waitForTimeout(2500);
  if (await page.locator('input[aria-label="Access code"]').count()) {
    throw new Error('the access gate is showing — the PIN would be filmed; aborting');
  }

  const times = {};
  t0 = Date.now();
  // Everything before this instant (load, zoom, gate check) is lead-in that has to be
  // trimmed off the front of the file before the captions line up.
  times._offset = Number(((t0 - videoStartedAt) / 1000).toFixed(2));
  console.log(`lead-in before beat 0: ${times._offset}s (trim this off the recording)`);
  for (const beat of beats) {
    await waitUntil(beat.start);
    times[beat.id] = Number(now().toFixed(2));
    console.log(`${times[beat.id].toFixed(1).padStart(6)}s  ${beat.id}  ${beat.title}  (planned ${beat.start}s)`);
    const action = ACTIONS[beat.id];
    if (action) {
      try { await action(page); } catch (e) { console.error(`   ! ${beat.id}: ${e.message}`); }
    }
    if (STOP_AFTER && beat.id === STOP_AFTER) break;
  }
  const tail = beats[beats.length - 1].end;
  if (!STOP_AFTER) await waitUntil(tail + 1.5);

  fs.writeFileSync(path.join(HERE, 'beat_times.json'), JSON.stringify(times, null, 1), 'utf8');
  const video = page.video();
  await ctx.close();                      // flushes the video file
  const file = video ? await video.path() : null;
  await browser.close();
  console.log('\nvideo:', file);
  console.log('beat_times.json written —', Object.keys(times).length, 'beats');
})().catch((e) => { console.error('ERR', e.stack || e.message); process.exit(1); });
